### ISSUE TITLE
Loading docker image from gcr.io: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by ghost** [apptainer/singularity#1628]
## Version of Singularity:

2.4.2-dist
2.5.1-dist

### Expected behavior

I attempt to download an image from the Google Cloud Registry:

    singularity pull docker://gcr.io/deepvariant-docker/deepvariant:0.4.1

[I am running this from within a docker container because I'm trying to do it on a Mac. I don't expect this to make a difference.]

### Actual behavior

Getting an SSL error:

```
root@f9c0b7542586:/# singularity pull docker://gcr.io/deepvariant-docker/deepvariant:0.4.1
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/singularity/python/import.py", line 109, in <module>
    main()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/import.py", line 86, in main
    layerfile=LAYERFILE)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/docker/main.py", line 85, in IMPORT
    client = DockerApiConnection(image=image, auth=auth)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/docker/api.py", line 92, in __init__
    self.load_image(kwargs['image'])
  File "/usr/lib/x86_64-linux-gnu/singularity/python/docker/api.py", line 146, in load_image
    self.update_token()
  File "/usr/lib/x86_64-linux-gnu/singularity/python/docker/api.py", line 191, in update_token
    response = self.get_tags(return_response=True)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/docker/api.py", line 314, in get_tags
    return_response=return_response)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 291, in get
    updating_token=updating_token)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 310, in submit_request
    response = safe_urlopen(request)
  File "/usr/lib/x86_64-linux-gnu/singularity/python/base.py", line 152, in safe_urlopen
    return opener.open(url, data=data)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
Cleaning up...
ERROR: pulling container failed!
```

### Steps to reproduce behavior

The above command fails. I tried to force non-HTTPS, but that also fails:

    SINGULARITY_NOHTTPS=1 singularity pull docker://gcr.io:80/deepvariant-docker/deepvariant:0.4.1

----

Since you don't encourage import from local docker tar files, as stated in issue  #933 , it would be very good if this could be fixed.

**Comment by ghost** [comment]
I just compiled the newest version of singularity from git. Getting a different error:

```
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: gcr.io/deepvariant-docker/deepvariant:0.4.1
ERROR MANIFEST_UNKNOWN: Manifest with tag '0.4.1' has media type 'application/vnd.docker.distribution.manifest.v2+json', but client accepts 'application/json'.
Cleaning up...
ERROR: pulling container failed!
```
I will close this issue, since the original problem I reported seems to be fixed.
