### ISSUE TITLE
Problem with running Jupyter with singularity 3.0.1

### ISSUE THREAD

**Issue by sfleisch** [apptainer/singularity#2418]
## Version of Singularity:
3.0.1-145.gc9822fe

### Expected behavior
jupyter lab starts up

### Actual behavior

Singularity tensorflow-1.12.0-10.0-7.3.img:~> jupyter --config-dir
/.jupyter
Singularity tensorflow-1.12.0-10.0-7.3.img:~> jupyter notebook
Traceback (most recent call last):
  File "/opt/anaconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1531, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 242, in initialize
    self.migrate_config()
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 168, in migrate_config
    migrate()
  File "/opt/anaconda3/lib/python3.6/site-packages/jupyter_core/migrate.py", line 247, in migrate
    with open(os.path.join(env['jupyter_config'], 'migrated'), 'w') as f:
OSError: [Errno 30] Read-only file system: '/.jupyter/migrated'

### Steps to reproduce behavior

1.  Start up container with Anaconda3 installed.
2. jupyter notebook (or lab)

### Workaround
export JUPYTER_CONFIG_DIR=$HOME/.jupyter (or something else on a filesystem that is mounted writeable in the image).
Can stick this in the build.
### Concerns
The existing /.jupyter has a notebook_config.py file.
```
import os
from IPython.lib import passwd

c.NotebookApp.ip = '*'
c.NotebookApp.port = int(os.getenv('PORT', 8888))
c.NotebookApp.open_browser = False
c.MultiKernelManager.default_kernel_name = 'python3'

# sets a password if PASSWORD is set in the environment
if 'PASSWORD' in os.environ:
  c.NotebookApp.password = passwd(os.environ['PASSWORD'])
  del os.environ['PASSWORD']

```
I think this is largely default behavior. Having to copy at image startup is problematical.

### What changed?
With singularity 2.6.0 (what we were using previously), /.jupyter is mounted writeable. Now it isn't.

**Comment by sfleisch** [comment]
*Chagrin* The problem is in my recipe file. I set the config directory as a holdover from building Docker images.

**Comment by GodloveD** [comment]
Glad you figured this out @sfleisch.  Hopefully having this recorded will help someone with a similar issue in the future.
