### ISSUE TITLE
Singularity exec does not exit despite error with command

### ISSUE THREAD

**Issue by chrarnold** [apptainer/singularity#2468]
## Version of Singularity:
singularity version 3.0.1-73.ga50b5b3.el7

### Expected behavior

singularity exec exist upon error with command

### Actual behavior

Singularity hangs and waits forever.

### Steps to reproduce behavior

I do have a reproducible case here. First,  download the two data files that are used as input, each is less than 500 KB
https://www.dropbox.com/s/b5k7k2ptynumfre/C103_rep2_1.fastq.gz?dl=0
https://www.dropbox.com/s/3592medmwsm2cle/C103_rep2_2.fastq.gz?dl=0

```
singularity pull shub://chrarnold/Singularity_images:rna_seq_conda
singularity exec Singularity_images_rna_seq_conda.sif bash -c 'fastqc -o output -t 2 --extract C103_rep2_1.fastq.gz C103_rep2_2.fastq.gz '
```

This should give the following output, with the hang happening in the end:

```
singularity exec Singularity_images_rna_seq_conda.sif bash -c 'fastqc -o output -t 2 --extract C103_rep2_1.fastq.gz C103_rep2_2.fastq.gz ' 
Started analysis of C103_rep2_1.fastq.gz
Approx 10% complete for C103_rep2_1.fastq.gz
Approx 20% complete for C103_rep2_1.fastq.gz
Approx 30% complete for C103_rep2_1.fastq.gz
Approx 40% complete for C103_rep2_1.fastq.gz
Approx 50% complete for C103_rep2_1.fastq.gz
Approx 60% complete for C103_rep2_1.fastq.gz
Approx 70% complete for C103_rep2_1.fastq.gz
Approx 80% complete for C103_rep2_1.fastq.gz
Approx 90% complete for C103_rep2_1.fastq.gz
Approx 100% complete for C103_rep2_1.fastq.gz
Analysis complete for C103_rep2_1.fastq.gz
Started analysis of C103_rep2_2.fastq.gz
Approx 10% complete for C103_rep2_2.fastq.gz
Approx 20% complete for C103_rep2_2.fastq.gz
Approx 30% complete for C103_rep2_2.fastq.gz
Approx 40% complete for C103_rep2_2.fastq.gz
Approx 50% complete for C103_rep2_2.fastq.gz
Approx 60% complete for C103_rep2_2.fastq.gz
Approx 70% complete for C103_rep2_2.fastq.gz
Approx 80% complete for C103_rep2_2.fastq.gz
Approx 90% complete for C103_rep2_2.fastq.gz
Approx 100% complete for C103_rep2_2.fastq.gz
Analysis complete for C103_rep2_2.fastq.gz
Exception in thread "Thread-2" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
	at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:856)
	at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.paint(QualityBoxPlot.java:88)
	at java.desktop/javax.swing.JComponent.print(JComponent.java:1220)
	at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:68)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 13 more
Caused by: java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 18 more
Exception in thread "Thread-1" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
	at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:856)
	at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.paint(QualityBoxPlot.java:88)
	at java.desktop/javax.swing.JComponent.print(JComponent.java:1220)
	at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:68)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 13 more
Caused by: java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 18 more

```

I am wondering who is to blame: Fastqc or Singularity, or even Java? Anyway, right now, this causes my workflows to hang indefinitely, and I'd like to find the reason and a solution.

Thanks for looking into this!

**Comment by chrarnold** [comment]
So when I execute that inside the container, the error is thrown, but ctrl+c aborts the command brings me back to the container, indicating that the command actually does not actually exit with any exit code. I guess Singularity is not to blame then, right, or could it still be some sort of Singularity bug as it is supposed to exit but does not? 

I have seen this "hang" also in a completely different program last week or so, there it was a python script, but with no error message being displayed, though. I cannot reproduce right now, but I am starting to wonder whether this is connected...

**Comment by jscook2345** [comment]
@chrarnold 

If the command does not exit `singularity` will not be able to know to exit either. My guess is that the command being run is hanging and causing the issue.

Feel free to update this issue or create a new one if you think you are experiencing more hangs though!

**Comment by cclerget** [comment]
Pretty sure (if it come from Singularity) it's fixed by newer releases. Closing. Feel free to ping to re-open if required.
