### ISSUE TITLE
Singularity can't run Clear Linux

### ISSUE THREAD

**Issue by omenos** [apptainer/singularity#2737]
## Version of Singularity:

3.0.3

### Expected behavior

The ability to run and shell into the container.

This is attempting to create Clear Linux containers using the Singularity runtime. So far I've attempted two methods, building directly from Docker and manually adding in missing files through a definition.

### Actual behavior

Singularity errors out.

Straight from Docker:
```text
$ singularity build --sandbox intel docker://clearlinux:latest
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
```

Definition File:
```text
=====
bootstrap: docker
from: clearlinux:latest

%post
    touch /etc/passwd
    touch /etc/group
=====

$ singularity shell intel
panic: runtime error: index out of range

goroutine 8 [running, locked to thread]:
github.com/sylabs/singularity/internal/pkg/util/fs/files.Passwd(0xc000366780, 0x2e, 0xc00034e240, 0xc, 0x3e8, 0xc0002db400, 0x0, 0x200, 0x0, 0x0)
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/pkg/util/fs/files/passwd.go:49 +0x860
github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity.(*container).addIdentityMount(0xc0000b4240, 0xc0003347a0, 0x0, 0x0)
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity/container.go:1592 +0x60d
github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity.(*container).addIdentityMount-fm(0xc0003347a0, 0x0, 0x0)
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity/container.go:103 +0x34
github.com/sylabs/singularity/internal/pkg/util/fs/mount.(*System).MountAll(0xc0003347a0, 0x9, 0x0)
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/pkg/util/fs/mount/system.go:78 +0x341
github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity.create(0xc0002d16f0, 0xc000334760, 0xf98, 0x7f7045c0c0b8, 0xc00000e9c8)
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity/container.go:151 +0x74d
github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity.(*EngineOperations).CreateContainer(0xc0002d16f0, 0xf98, 0xa77cc0, 0xc00000e9c8, 0x0, 0x0)
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/pkg/runtime/engines/singularity/create.go:86 +0x3f3
github.com/sylabs/singularity/internal/app/starter.Master.func1(0x6, 0xc00020afc0, 0xc000201d80, 0xf98)
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/app/starter/master.go:46 +0x185
created by github.com/sylabs/singularity/internal/app/starter.Master
    /home/mroche/rpmbuild/BUILD/singularity-3.0.3/gopath/src/github.com/sylabs/singularity/internal/app/starter/master.go:36 +0x1a3
```

### Steps to reproduce behavior

Create a Clear Linux container by any means.

**Comment by truatpasteurdotfr** [comment]
it seems to somehow work for 3.0.2 on a CentOS-7 host for both sif file and sandbox.
```
[tru@sillage docker-clearlinux]$ sudo singularity build docker-clearlinux.sif Singularity 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:c447a86b3cb6b2c2a1c6f6e936ae490b686024b4ac3ce099120a0b1dd55486da
 40.86 MiB / 40.86 MiB [====================================================] 1s
Copying config sha256:3c6a2fe6846f99c53363475e4a25ada23dc524c0fd9d9eb8ebd13180329dd348
 1012 B / 1012 B [==========================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: docker-clearlinux.sif
[tru@sillage docker-clearlinux]$ singularity shell docker-clearlinux.sif 
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
Singularity docker-clearlinux.sif:~/singularity.d/docker-clearlinux> df
...
```
and
```
[tru@sillage docker-clearlinux]$ singularity build --sandbox intel docker://clearlinux:latest
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:c447a86b3cb6b2c2a1c6f6e936ae490b686024b4ac3ce099120a0b1dd55486da
 40.86 MiB / 40.86 MiB [====================================================] 1s
Copying config sha256:3c6a2fe6846f99c53363475e4a25ada23dc524c0fd9d9eb8ebd13180329dd348
 1012 B / 1012 B [==========================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating sandbox directory...
INFO:    Build complete: intel
[tru@sillage docker-clearlinux]$  singularity shell intel
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
Singularity intel:~/singularity.d/docker-clearlinux> panic: runtime error: index ou
bash: panic:: command not found
Singularity intel:~/singularity.d/docker-clearlinux> df /
Filesystem     1K-blocks  Used Available Use% Mounted on
overlay            16384     4     16380   1% /
Singularity intel:~/singularity.d/docker-clearlinux> 

```

**Comment by omenos** [comment]
Maybe a random regression in 3.0.3? I wonder if 3.1.0 is affected...

**Comment by truatpasteurdotfr** [comment]
upgraded to 3.0.3 on C7 and no error (no panic printed) for both
```
[tru@sillage docker-clearlinux]$  singularity build --sandbox intel docker://clearlinux:latest
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:c447a86b3cb6b2c2a1c6f6e936ae490b686024b4ac3ce099120a0b1dd55486da
Copying config sha256:3c6a2fe6846f99c53363475e4a25ada23dc524c0fd9d9eb8ebd13180329dd348
 1012 B / 1012 B [==========================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating sandbox directory...
INFO:    Build complete: intel
[tru@sillage docker-clearlinux]$ singularity shell intel/
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
Singularity intel:~/singularity.d/docker-clearlinux> exit
[tru@sillage docker-clearlinux]$ sudo singularity build docker-clearlinux-latest.sif Singularity 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:c447a86b3cb6b2c2a1c6f6e936ae490b686024b4ac3ce099120a0b1dd55486da
Copying config sha256:3c6a2fe6846f99c53363475e4a25ada23dc524c0fd9d9eb8ebd13180329dd348
 1012 B / 1012 B [==========================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: docker-clearlinux-latest.sif
[tru@sillage docker-clearlinux]$ singularity shell docker-clearlinux-latest.sif
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
Singularity docker-clearlinux-latest.sif:~/singularity.d/docker-clearlinux> exit

```

**Comment by truatpasteurdotfr** [comment]
[tru@sillage bin]$ type go
go is /usr/bin/go
[tru@sillage bin]$ rpm -qf /usr/bin/go
golang-bin-1.11.2-3.el7.x86_64

**Comment by omenos** [comment]
Weird, I'm running CentOS 7.6 myself. I didn't use EPEL's golang package, I used the package from the golang site.

**Comment by cclerget** [comment]
@omento #2738 should fix the issue, if you can give it a try. Thanks !

**Comment by omenos** [comment]
@jmstover Should I pull this into the 3.1.0-rc3 branch? I plan on adding 3.1.0 to the cluster when it's out, but for testing purposes would it be okay to patch the 3.0 branch?

**Comment by jmstover** [comment]
This should probably get tagged for 3.1.0 ...  @cclerget @GodloveD @bauerm97  

@omento ... if you base off the master branch you should be fine.
