### ISSUE TITLE
pulling Docker container from remote hub fails with " KeyError: 'runtime_dir' " trying to create a directory

### ISSUE THREAD

**Issue by thdesy** [apptainer/singularity#2882]
## Version of Singularity:

3.1.0-1.el7

### Expected behavior

with 2.6.1-1.1.el7  pulling a container in a user context worked fine with something like
```
 2.6 > singularity run --nv --contain --bind /afs:/afs,/nfs:/nfs,/cvmfs:/cvmfs,/pnfs:/pnfs docker://gitlab-registry.cern.ch/cpollard/atlasml:latest
Docker image path: gitlab-registry.cern.ch/cpollard/atlasml:latest
Cache folder set to /nfs/dust/atlas/user/hartmath/container/cache/docker
[16/16] |===================================| 100.0% 
Creating container runtime...
Exploding layer: sha256:18d680d616571900d78ee1c8fff0310f2a2afe39c6ed0ba2651ff667af406c3e.tar.gz
...
```
### Actual behavior

with 3.1.0 'mkdir(name, mode)' fails as '/run/user' is r/o (according to the dump)

```
 3.1 > singularity run --nv --contain --bind /afs:/afs --bind /nfs:/nfs --bind /cvmfs:/cvmfs --bind /pnfs:/pnfs docker://gitlab-registry.cern.ch/cpollard/atlasml:latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</usr/local/lib/python3.5/dist-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1626, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1319, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/run/user'
```

Cheers
  Thomas

**Comment by bauerm97** [comment]
Hi @thdesy, by default in the 3.x series Docker-like images are cached as SIF images. Try running the same command but adding `--writable-tmpfs` to it. It should work after that. If it doesn't, please ping me and we'll take a deeper look

**Comment by thdesy** [comment]
Hi @bauerm97,

unfortunately also with --writable-tmpfs the behaviour looks the same (singularity version 3.1.0-1.el7)

```
3.1> singularity run --writable-tmpfs --nv --contain --bind /afs:/afs --bind /nfs:/nfs --bind /cvmfs:/cvmfs --bind /pnfs:/pnfs docker://gitlab-registry.cern.ch/cpollard/atlasml:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:18d680d616571900d78ee1c8fff0310f2a2afe39c6ed0ba2651ff667af406c3e
 41.34 MiB / 41.34 MiB [====================================================] 1s
...
 10.53 KiB / 10.53 KiB [====================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /var/tmp/hartmath/cache/oci-tmp/649e6cff5d1512b7d55a8d041ea8e54245a5c508ab74eb403fe9a54aece90291/atlasml_latest.sif
INFO:    Image cached as SIF at /var/tmp/hartmath/cache/oci-tmp/649e6cff5d1512b7d55a8d041ea8e54245a5c508ab74eb403fe9a54aece90291/atlasml_latest.sif
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</usr/local/lib/python3.5/dist-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1626, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1319, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/user'
```

the container is not mine but a user's - I have to check, what it is actually doing in detail, but so far it worked without issues with Singularity v2.6. 

I just tried the container: /run exists in the container's namespace and I could create dir '/run/users' - however, I have no idea, where the directory ends up in the host namespace.
/run should (in principle) not be bound to something writable and I do not find anything in SINGULARITY_{TMP,CACHE}DIR looking suspicious.

```
2.6 > singularity shell --nv --containall --bind /afs:/afs --bind /nfs:/nfs --bind /cvmfs:/cvmfs --bind /pnfs:/pnfs docker://gitlab-registry.cern.ch/cpollard/atlasml:latest
Docker image path: gitlab-registry.cern.ch/cpollard/atlasml:latest
Cache folder set to /nfs/dust/atlas/user/hartmath/container/cache/docker
Creating container runtime...
...
Singularity atlasml:latest:~> ls /run
init.upgraded  lock  mount  screen  secrets  systemd  utmp
Singularity atlasml:latest:~> mkdir /run/user
Singularity atlasml:latest:~> echo $?
0
Singularity atlasml:latest:~> echo "hiho" > /run/user/test
Singularity atlasml:latest:~> cat /run/user/test
hiho
```

**Comment by thdesy** [comment]
how does it work in 2.6??
