### ISSUE TITLE
Really ugly / scary error again!

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3777]
## Version of Singularity:

I am working on the version that @cclerget released the networking fix for.

I don't think I can give exact steps to reproduce, but I was developing a singularity-compose app, and just finish build (without fakeroot) for two containers, rstudio an nginx. I ran singularity-compose up to bring them up, and this resulted almost immediately:

```bash
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f0b91139e97 m=10 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f0b91139e97
stack: frame={sp:0x7f0b763cf7b0, fp:0x0} stack=[0x7f0b75bd0268,0x7f0b763cfe68)
00007f0b763cf6b0:  3fe5b7cf9f3e7cfa  0000000000000000 
00007f0b763cf6c0:  41258c6000000000  0000000000000000 
00007f0b763cf6d0:  00007f0b60000010  00007f0b60000010 
00007f0b763cf6e0:  000000000000000e  000000000000000e 
00007f0b763cf6f0:  0000000000000000  0000000000000000 
00007f0b763cf700:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf710:  0000000400000004  0000000400000004 
00007f0b763cf720:  00007f0b60000800  00007f0b60000800 
00007f0b763cf730:  0001020304050607  08090a0b0c0d0e0f 
00007f0b763cf740:  656c6361726f2d38  6e69622f65726a2f 
00007f0b763cf750:  762f656d6f682f3a  442f617373656e61 
00007f0b763cf760:  73746e656d75636f  637375626f6c672f 
00007f0b763cf770:  65707463656e6e6f  322d6c616e6f7372 
00007f0b763cf780:  73752f3a332e332e  2f6c61636f6c2f72 
00007f0b763cf790:  2f3a6e69622f6f67  6e61762f656d6f68 
00007f0b763cf7a0:  0000000000000000  0000000000000000 
00007f0b763cf7b0: <0000000000000000  0000000000000000 
00007f0b763cf7c0:  0000000000000000  0000000000000000 
00007f0b763cf7d0:  0000000000000000  0000000000000000 
00007f0b763cf7e0:  0000000000000000  0000000000000000 
00007f0b763cf7f0:  0000000000000000  0000000000000000 
00007f0b763cf800:  0000000000000002  800000000000000e 
00007f0b763cf810:  0000000000000000  0000000000000000 
00007f0b763cf820:  0000000000000000  0000000000000000 
00007f0b763cf830:  fffffffe7fffffff  ffffffffffffffff 
00007f0b763cf840:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf850:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf860:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf870:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf880:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf890:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf8a0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f0b91139e97
stack: frame={sp:0x7f0b763cf7b0, fp:0x0} stack=[0x7f0b75bd0268,0x7f0b763cfe68)
00007f0b763cf6b0:  3fe5b7cf9f3e7cfa  0000000000000000 
00007f0b763cf6c0:  41258c6000000000  0000000000000000 
00007f0b763cf6d0:  00007f0b60000010  00007f0b60000010 
00007f0b763cf6e0:  000000000000000e  000000000000000e 
00007f0b763cf6f0:  0000000000000000  0000000000000000 
00007f0b763cf700:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf710:  0000000400000004  0000000400000004 
00007f0b763cf720:  00007f0b60000800  00007f0b60000800 
00007f0b763cf730:  0001020304050607  08090a0b0c0d0e0f 
00007f0b763cf740:  656c6361726f2d38  6e69622f65726a2f 
00007f0b763cf750:  762f656d6f682f3a  442f617373656e61 
00007f0b763cf760:  73746e656d75636f  637375626f6c672f 
00007f0b763cf770:  65707463656e6e6f  322d6c616e6f7372 
00007f0b763cf780:  73752f3a332e332e  2f6c61636f6c2f72 
00007f0b763cf790:  2f3a6e69622f6f67  6e61762f656d6f68 
00007f0b763cf7a0:  0000000000000000  0000000000000000 
00007f0b763cf7b0: <0000000000000000  0000000000000000 
00007f0b763cf7c0:  0000000000000000  0000000000000000 
00007f0b763cf7d0:  0000000000000000  0000000000000000 
00007f0b763cf7e0:  0000000000000000  0000000000000000 
00007f0b763cf7f0:  0000000000000000  0000000000000000 
00007f0b763cf800:  0000000000000002  800000000000000e 
00007f0b763cf810:  0000000000000000  0000000000000000 
00007f0b763cf820:  0000000000000000  0000000000000000 
00007f0b763cf830:  fffffffe7fffffff  ffffffffffffffff 
00007f0b763cf840:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf850:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf860:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf870:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf880:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf890:  ffffffffffffffff  ffffffffffffffff 
00007f0b763cf8a0:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc00043c360, 0xc0004401e0, 0x0, 0xc000245860, 0x5, 0xc0002458a0, 0x18, 0x0, 0x0, 0x756ea1c5628b01)
	/usr/local/go/src/net/http/transport.go:1004 +0x58e
net/http.(*Transport).roundTrip(0xc00043c360, 0xc00044d600, 0x203000, 0xc0004ca0f0, 0xaf340d)
	/usr/local/go/src/net/http/transport.go:451 +0x690
net/http.(*Transport).RoundTrip(0xc00043c360, 0xc00044d600, 0xc00043c360, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc00044d600, 0x12e0140, 0xc00043c360, 0x0, 0x0, 0x0, 0xc00000e520, 0xc000440120, 0xc0004ca180, 0x1)
	/usr/local/go/src/net/http/client.go:250 +0x14b
net/http.(*Client).send(0xc0004400f0, 0xc00044d600, 0x0, 0x0, 0x0, 0xc00000e520, 0x0, 0x1, 0xc000354380)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc0004400f0, 0xc00044d600, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x2a8
net/http.(*Client).Do(0xc0004400f0, 0xc00044d600, 0xc0004ca3e8, 0x2, 0x2)
	/usr/local/go/src/net/http/client.go:509 +0x35
github.com/containers/image/docker.(*dockerClient).makeRequestToResolvedURL(0xc0000f2180, 0x12ef780, 0xc0000be038, 0x11c447f, 0x3, 0xc000245860, 0x20, 0x0, 0x0, 0x0, ...)
	vendor/github.com/containers/image/docker/docker_client.go:386 +0x3db
github.com/containers/image/docker.(*dockerClient).detectProperties.func1(0x11c5b16, 0x5, 0x0, 0x0)
	vendor/github.com/containers/image/docker/docker_client.go:490 +0x1c5
github.com/containers/image/docker.(*dockerClient).detectProperties(0xc0000f2180, 0x12ef780, 0xc0000be038, 0x11a4540, 0x1c)
	vendor/github.com/containers/image/docker/docker_client.go:505 +0xb6
github.com/containers/image/docker.(*dockerClient).makeRequest(0xc0000f2180, 0x12ef780, 0xc0000be038, 0x11c447f, 0x3, 0xc0002ee240, 0x22, 0xc000558868, 0x0, 0x0, ...)
	vendor/github.com/containers/image/docker/docker_client.go:350 +0x5a
github.com/containers/image/docker.(*dockerImageSource).fetchManifest(0xc000083400, 0x12ef780, 0xc0000be038, 0x11c6ecb, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	vendor/github.com/containers/image/docker/docker_image_src.go:92 +0x2ad
github.com/containers/image/docker.(*dockerImageSource).ensureManifestIsLoaded(0xc000083400, 0x12ef780, 0xc0000be038, 0x12e4c80, 0xc00000d3a0)
	vendor/github.com/containers/image/docker/docker_image_src.go:124 +0x92
github.com/containers/image/docker.(*dockerImageSource).GetManifest(0xc000083400, 0x12ef780, 0xc0000be038, 0x0, 0x12f4580, 0xc000083400, 0x0, 0x0, 0xc000380470, 0x0, ...)
	vendor/github.com/containers/image/docker/docker_image_src.go:81 +0x57
github.com/sylabs/singularity/internal/pkg/client/oci.calculateRefHash(0x12f85a0, 0xc000380470, 0xc000412dc0, 0xc00000d3a0, 0x12f85a0, 0xc000380470, 0x0)
	internal/pkg/client/oci/oci.go:119 +0xb6
github.com/sylabs/singularity/internal/pkg/client/oci.ConvertReference(0x12f85a0, 0xc000380470, 0xc000412dc0, 0xc000380470, 0x0, 0x0, 0x7)
	internal/pkg/client/oci/oci.go:36 +0x49
github.com/sylabs/singularity/internal/pkg/build/sources.(*OCIConveyorPacker).Get(0xc00044f930, 0xc00014c000, 0x0, 0x0)
	internal/pkg/build/sources/conveyorPacker_oci.go:124 +0x668
github.com/sylabs/singularity/internal/pkg/build.(*Build).Full(0xc00043b680, 0x0, 0x0)
	internal/pkg/build/build.go:198 +0x4b4
github.com/sylabs/singularity/cmd/internal/cli.run(0x1aed980, 0xc0003716e0, 0x2, 0x3)
	cmd/internal/cli/build_linux.go:154 +0x4a0
github.com/spf13/cobra.(*Command).execute(0x1aed980, 0xc0000c8020, 0x3, 0x3, 0x1aed980, 0xc0000c8020)
	vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1af6340, 0x81cd0b, 0x7f0b91d02000, 0x0)
	vendor/github.com/spf13/cobra/command.go:850 +0x2f8
github.com/sylabs/singularity/cmd/internal/cli.ExecuteSingularity()
	cmd/internal/cli/singularity.go:246 +0x133
main.main()
	cmd/singularity/cli.go:17 +0x20

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 9 [chan receive]:
github.com/sylabs/singularity/internal/pkg/build.(*Build).Full.func1(0xc000042420, 0xc00043b680)
	internal/pkg/build/build.go:169 +0x45
created by github.com/sylabs/singularity/internal/pkg/build.(*Build).Full
	internal/pkg/build/build.go:168 +0x156

goroutine 10 [chan receive]:
net/http.(*persistConn).addTLS(0xc00043c480, 0xc0002458a0, 0x14, 0x0, 0xc0002458b5, 0x3)
	/usr/local/go/src/net/http/transport.go:1177 +0x1a7
net/http.(*Transport).dialConn(0xc00043c360, 0x12ef780, 0xc0000be038, 0x0, 0xc000245860, 0x5, 0xc0002458a0, 0x18, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1250 +0x15ad
net/http.(*Transport).getConn.func4(0xc00043c360, 0x12ef780, 0xc0000be038, 0xc000440210, 0xc0000425a0)
	/usr/local/go/src/net/http/transport.go:999 +0x6e
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:998 +0x3d7

goroutine 52 [running]:
	goroutine running on other thread; stack unavailable
created by net/http.(*persistConn).addTLS
	/usr/local/go/src/net/http/transport.go:1167 +0x17e

rax    0x0
rbx    0x7f0b763cfd28
rcx    0x7f0b91139e97
rdx    0x0
rdi    0x2
rsi    0x7f0b763cf7b0
rbp    0x7f0b763cfae0
rsp    0x7f0b763cf7b0
r8     0x0
r9     0x7f0b763cf7b0
r10    0x8
r11    0x246
r12    0x30
r13    0x11
r14    0x12d1720
r15    0x0
```
The only thing I can think of is that it's related to the /init script in rocker/tidyverse, which gave me trouble years ago when I attempted using for Singularity. Is there any way (for someone that knows the logic of the golang modules) to look at the error above and try to guess what happened? My only guess is that starting the instances with sudo (and thus running the startscript with sudo) and calling the /init led to this trouble. For completeness, I shelled into the Docker container to take a look at what init does (and this totally brought back memories for when I did this the first time and equally screwed up my machine!)

```bash
#!/bin/execlineb -S0

##
## load default PATH (the same that Docker includes if not provided) if it doesn't exist,
## then go ahead with stage1.
## this was motivated due to this issue:
## - https://github.com/just-containers/s6-overlay/issues/108
##


/bin/importas -D /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PATH PATH
export PATH ${PATH}
/etc/s6/init/init-stage1 $@
``` 
And then in `/etc/s6/init/init-stage1`
```bash
#!/bin/execlineb -S0

##
## load default PATH (the same that Docker includes if not provided) if it doesn't exist,
## then go ahead with stage1.
## this was motivated due to this issue:
## - https://github.com/just-containers/s6-overlay/issues/108
##


/bin/importas -D /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PATH PATH
export PATH ${PATH}
/etc/s6/init/init-stage1 $@
root@b91aa5cc5178:/# cat /etc/s6/init/init-stage1
#!/bin/execlineb -S0

##
## dump environment into an envdir if S6_KEEP_ENV is unset
##

getcwd CWD

importas -D 0 S6_KEEP_ENV S6_KEEP_ENV
define -s DO_NOT_KEEP_ENV "s6-test ${S6_KEEP_ENV} -eq 0"
if
{
  ifelse { ${DO_NOT_KEEP_ENV} }
  {
    if { s6-rmrf /var/run/s6/container_environment }
    if { s6-mkdir -pm 0755 -- /var/run/s6/container_environment }
    s6-dumpenv -- /var/run/s6/container_environment
  }
  exit 0
}

##
## create env folder for each init stage, although stage1 is always copied from
## /etc/s6/init/env, it's made available in /var/run/s6/env-stage1 just for
## consistency.
##

if
{
  elglob -0 -- envdirs /var/run/s6/env-*
  forx -p -- envdir { ${envdirs} }
  importas -u envdir envdir
  s6-rmrf ${envdir}
}
if { s6-mkdir -pm 0755 -- /var/run/s6 }
if { s6-hiercopy /etc/s6/init/env /var/run/s6/env-stage1 }
if { s6-mkdir -pm 0755 -- /var/run/s6/env-stage2 }
if { s6-mkdir -pm 0755 -- /var/run/s6/env-stage3 }


##
## run everything else with only the environment defined in
## /var/run/s6/env-stage1 if we are not instructed to keep
## docker env. Programs can get back the container
## environment by using "with-contenv program".
##

ifthenelse -s { ${DO_NOT_KEEP_ENV} }
{
  exec -c --
  s6-envdir /var/run/s6/env-stage1
}
{ }

backtick -n S6_CMD_ARG0 { printcontenv S6_CMD_ARG0 }
importas -d "\n" -s -u S6_CMD_ARG0 S6_CMD_ARG0

##
## route based on what was provided in S6_LOGGING
##

backtick -D 0 -n S6_LOGGING { printcontenv S6_LOGGING }
importas -u S6_LOGGING S6_LOGGING
ifelse { s6-test ${S6_LOGGING} -ne 0 }
{
  /etc/s6/init-catchall/init-stage1 ${S6_CMD_ARG0} $@
}
/etc/s6/init-no-catchall/init-stage1 ${S6_CMD_ARG0} $@
```
and then in `/etc/s6/init-no-catchall/init-stage1`

```
#!/bin/execlineb -S0

##
## init the scandir with our base services
##

if { s6-rmrf /var/run/s6/services }
if { s6-hiercopy /etc/s6/services /var/run/s6/services }
if { s6-rmrf /var/run/s6/services/s6-svscan-log }


##
## ensure our vital fifo exists
##

if { s6-rmrf /var/run/s6/services/s6-fdholderd/supervise/control }
if { s6-mkfifo -m 0600 /var/run/s6/services/s6-fdholderd/supervise/control }


##
## fork the "init-stage2" script
##

background
{
  # block until the supervision tree is running
  redirfd -w 3 /var/run/s6/services/s6-fdholderd/supervise/control
  fdclose 3

  # add some environment
  s6-envdir -- /etc/s6/init/env-stage2

  # run the script
  /etc/s6/init-no-catchall/init-stage2 $@
}
unexport !


##
## run the rest of stage 1 with sanitized descriptors
##

redirfd -r 0 /dev/null


##
## start the supervision tree
##

s6-svscan -t0 /var/run/s6/services
```

Could [this](https://skarnet.org/software/s6/s6-svscan.html) have interfered with my host (or the instances) since being run with sudo? Note that I (rather stupidly) tried again without sudo, and the containers were brought up (but then I couldn't stop them). I think it could just be the case that the initial error still persisted, but I've already restarted and I don't want to test that again :)

**Comment by vsoch** [comment]
Here is what the logs look like

```
rstudio OUT
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 
USER is now root
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.


rstudio ERR
usermod: user 'root' already exists
groupmod: group 'root' already exists

```

**Comment by cclerget** [comment]
@vsoch You've reached the number of process limit, I think you encounter the same issue as : https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel

**Comment by vsoch** [comment]
yes! Those messages look exactly like what happened. So - based on the s6-svscan - is it the case (do you think) that normally we don't reach a process limit because (whatever that command does) is isolated to the container? What is the lesson we should take away here - not to use this particular tool, or something else?

**Comment by vsoch** [comment]
Also for completeness of the issue (and someone in the future can know the resolution), I was able to get this all working simply by getting rid of the /init script, and just starting rstudio in the startscript:

```
%startscript
  rstudio-server start
```

Full stuffs here https://github.com/singularityhub/singularity-compose-examples/tree/master/rstudio-simple. I'm not sure why some of these Docker containers have such complicated entrypoint commands, but I think what I've learned is to try simpler solutions first.

**Comment by cclerget** [comment]
Looks like s6-svscan didn't help but the guilty is systemd, for what you are trying to do on your machine and from the error above you should configure docker (if you are running singularity compose from a docker container) or increase the value for `ulimit -u` (look at systemd limits applied also) in order to increase the number of processes you can execute on your machine. This is not a Singularity/Golang/Docker/Container issue.

**Comment by vsoch** [comment]
Oh I wasn't using Docker, that was the startscript for a Singularity instance, all running on my host.

**Comment by cclerget** [comment]
What's the output of `systemctl show` ?

**Comment by vsoch** [comment]
A ton of stuff!

*removed in case privacy stuffs in there*

**Comment by cclerget** [comment]
Try by adding in `/etc/systemd/user.conf` this line : `DefaultTasksMax=infinity` and retry your example after you rebooted your machine

**Comment by vsoch** [comment]
okay! I'll need to try this a bit later - I have a few interactive sessions I'm working on for a package and I don't want to lose the state. Thanks @cclerget :)

**Comment by vsoch** [comment]
And as for the issue, I'm happy to close it, because I have an understanding of the cause, and a fix. Thanks again @cclerget, closing.
