### ISSUE TITLE
Out of memory exception when remote building

### ISSUE THREAD

**Issue by bgbrink** [apptainer/singularity#4394]
## Version of Singularity:

https://cloud.sylabs.io/builder

### Expected behavior

I am trying to build this definition with the remote builder:
```
Bootstrap: docker
From: sangerpathogens/companion

%environment
  PATH=$PWD/companion/bin:$PATH
  export PATH

%post
  chmod -R 777 /opt
```

### Actual behavior
After pulling the docker and creating the SIF, I get an out of memory exception:
[build.log](https://github.com/sylabs/singularity/files/3582360/build.log)

**Comment by dtrudg** [comment]
Hello @bgbrink - am afraid this is related to issue #4393 and work to fix is in progress. Apologies for the inconvenience.

**Comment by dmey** [comment]
@dctrud @EmmEff #4393 did not do it for me --still same issue when building from master (singularity version 3.4.0-246.g5e08a99da):

Log tail:
```
INFO:    Adding environment to container
INFO:    Creating SIF file...
INFO:    Build complete: /tmp/image-303675658
WARNING: Skipping container verifying
 512.00 MiB / 1.20 GiB   41.62% 372.95 MiB/s 00m01sfatal error: runtime: out of memory

runtime stack:
runtime.throw(0x131262e, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc084000000, 0x80000000, 0x1db1eb8)
        /usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x1d98b00, 0x80000000, 0x1d98b10, 0x40000)
        /usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x1d98b00, 0x40000, 0x0)
        /usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x1d98b00, 0x40000, 0x1db1ec8, 0x100000081)
        /usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x1d98b00, 0x40000, 0x820101, 0xc00047c148)
        /usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x1d98b00, 0x40000, 0x7fe5e9010101, 0x857e06)
        /usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x7ffffe00, 0xc000040101, 0xc000000180)
        /usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc0003091c0 sp=0xc0003091b8 pc=0x879a30
runtime.mallocgc(0x7ffffe00, 0x119fe00, 0x20000001, 0xc000309298)
        /usr/local/go/src/runtime/malloc.go:949 +0x872 fp=0xc000309260 sp=0xc0003091c0 pc=0x82d822
runtime.makeslice(0x119fe00, 0x7ffffe00, 0x7ffffe00, 0x0)
        /usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc000309290 sp=0xc000309260 pc=0x864b3c
bytes.makeSlice(0x7ffffe00, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:232 +0x6d fp=0xc0003092c0 sp=0xc000309290 pc=0x8a1c1d
bytes.(*Buffer).grow(0xc0003093b0, 0x200, 0x20000000)
        /usr/local/go/src/bytes/buffer.go:145 +0x16f fp=0xc000309310 sp=0xc0003092c0 pc=0x8a155f
bytes.(*Buffer).ReadFrom(0xc0003093b0, 0x147c000, 0xc0005013e0, 0x7fe5fc65a240, 0x0, 0xc0003913d8)
        /usr/local/go/src/bytes/buffer.go:205 +0x4b fp=0xc000309380 sp=0xc000309310 pc=0x8a1a0b
io/ioutil.readAll(0x147c000, 0xc0005013e0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:36 +0xe5 fp=0xc0003093e8 sp=0xc000309380 pc=0x9e8b95
io/ioutil.ReadAll(...)
        /usr/local/go/src/io/ioutil/ioutil.go:45
github.com/hashicorp/go-retryablehttp.NewRequest(0x12fc5aa, 0x3, 0xc0001701c0, 0x1ae, 0x1204140, 0xc0005013e0, 0x0, 0xc0001a6800, 0x1e5)
        vendor/github.com/hashicorp/go-retryablehttp/client.go:185 +0x5d0 fp=0xc0003094f8 sp=0xc0003093e8 pc=0xd47790
github.com/sylabs/scs-library-client/client.(*Client).postFileV2(0xc0001fcb00, 0x149c040, 0xc00010b200, 0x147c660, 0xc0000b43d0, 0x4ce2b000, 0xc00052dc00, 0x18, 0x1497480, 0xc000524b80, ...)
        vendor/github.com/sylabs/scs-library-client/client/push.go:274 +0x44c fp=0xc0003096a0 sp=0xc0003094f8 pc=0xd515fc
github.com/sylabs/scs-library-client/client.(*Client).UploadImage(0xc0001fcb00, 0x149c040, 0xc00010b200, 0x148a540, 0xc0000b43d0, 0xc0002a2f90, 0x2e, 0xc00051d490, 0x1, 0x1, ...)
        vendor/github.com/sylabs/scs-library-client/client/push.go:176 +0x1308 fp=0xc0003099d8 sp=0xc0003096a0 pc=0xd505c8
github.com/sylabs/singularity/internal/app/singularity.LibraryPush(0x7ffcf324de3f, 0x14, 0x7ffcf324de54, 0x3f, 0xc000108000, 0x234, 0xc00052c100, 0x19, 0xc00054e2a0, 0x16, ...)
        internal/app/singularity/push.go:100 +0x808 fp=0xc000309bd8 sp=0xc0003099d8 pc=0x10acbd8
github.com/sylabs/singularity/cmd/internal/cli.glob..func64(0x1d4cba0, 0xc00023faa0, 0x2, 0x3)
        cmd/internal/cli/push.go:78 +0x16a fp=0xc000309cd8 sp=0xc000309bd8 pc=0x10d994a
github.com/spf13/cobra.(*Command).execute(0x1d4cba0, 0xc0000ba020, 0x3, 0x3, 0x1d4cba0, 0xc0000ba020)
        vendor/github.com/spf13/cobra/command.go:830 +0x2ae fp=0xc000309dc0 sp=0xc000309cd8 pc=0xa42a7e
github.com/spf13/cobra.(*Command).ExecuteC(0x1d4e720, 0xc0004c1f08, 0x4, 0x4)
        vendor/github.com/spf13/cobra/command.go:914 +0x2fc fp=0xc000309e98 sp=0xc000309dc0 pc=0xa436dc
github.com/sylabs/singularity/cmd/internal/cli.ExecuteSingularity()
        cmd/internal/cli/singularity.go:246 +0x159 fp=0xc000309f88 sp=0xc000309e98 pc=0x10d0059
main.main()
        cmd/singularity/cli.go:17 +0x20 fp=0xc000309f98 sp=0xc000309f88 pc=0x10dd7d0
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000309fe0 sp=0xc000309f98 pc=0x8508ac
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000309fe8 sp=0xc000309fe0 pc=0x87bb01

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 43 [select]:
net/http.(*persistConn).writeLoop(0xc00048dd40)
        /usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1358 +0xb0d

goroutine 28 [IO wait]:
internal/poll.runtime_pollWait(0x7fe5fc6acf08, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000d0918, 0x72, 0xe00, 0xe96, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000d0900, 0xc000342000, 0xe96, 0xe96, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000d0900, 0xc000342000, 0xe96, 0xe96, 0x203000, 0x0, 0xc000000031)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000b4500, 0xc000342000, 0xe96, 0xe96, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc000524820, 0xc000342000, 0xe96, 0xe96, 0x3, 0xa, 0xc000065938)
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0001033d8, 0x147b040, 0xc000524820, 0x82b3a5, 0x12034c0, 0x12cebe0)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc000103180, 0x147c360, 0xc0000b4500, 0x5, 0xc0000b4500, 0x203000)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc000103180, 0x1361500, 0xc0001032b8, 0xc000065b88)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc000103180, 0xc000343000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*persistConn).Read(0xc0000cefc0, 0xc000343000, 0x1000, 0x1000, 0xc000065c88, 0x8266e5, 0xc00029c360)
        /usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc00007ecc0)
        /usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc00007ecc0, 0x1, 0x0, 0x0, 0x1, 0xc00029c400, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0000cefc0)
        /usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 29 [select]:
net/http.(*persistConn).writeLoop(0xc0000cefc0)
        /usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1358 +0xb0d

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0x7fe5fc6ace38, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000d1318, 0x72, 0xe00, 0xe92, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000d1300, 0xc00052b000, 0xe92, 0xe92, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000d1300, 0xc00052b000, 0xe92, 0xe92, 0x203000, 0x0, 0xc000000035)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000b4510, 0xc00052b000, 0xe92, 0xe92, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc0005012a0, 0xc00052b000, 0xe92, 0xe92, 0x3, 0xa, 0xc000068938)
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00047ccd8, 0x147b040, 0xc0005012a0, 0x82b3a5, 0x12034c0, 0x12cebe0)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00047ca80, 0x147c360, 0xc0000b4510, 0x5, 0xc0000b4510, 0x203000)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00047ca80, 0x1361500, 0xc00047cbb8, 0xc000068b88)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00047ca80, 0xc0003ba000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*persistConn).Read(0xc00048dd40, 0xc0003ba000, 0x1000, 0x1000, 0xc000068c88, 0x8266e5, 0xc00029d020)
        /usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc000383320)
        /usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc000383320, 0x1, 0x0, 0x0, 0x1, 0xc000284200, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc00048dd40)
        /usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 52 [select]:
gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).refresher(0xc00059cb00)
        vendor/gopkg.in/cheggaaa/pb.v1/pb.go:493 +0xd2
created by gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Start
        vendor/gopkg.in/cheggaaa/pb.v1/pb.go:124 +0xb6
FATAL:   While performing build: build image size <= 0
```

**Comment by EmmEff** [comment]
@dmey the stack trace above references the Go module `go-retryablehttp`, which was removed by this patch. My recommendation would be to run `git clean -fdx -n` (remove `-n` once you've validated the files that will be removed) and then rebuild.

**Comment by dmey** [comment]
> My recommendation would be to run git clean -fdx -n (remove -n once you've validated the files that will be removed) and then rebuild.

@EmmEff tried with the above or even re-cloning the repo but getting the same issue. Is there a diagnostic we can run to see if/why `go-retryablehttp` gets picked up at build. (FYI using `go version go1.13 linux/amd64` on `Ubuntu 18.04.3 LTS`. Installed Singularity using instructions from [INSTALL.md](https://github.com/sylabs/singularity/blob/master/INSTALL.md#compiling-singularity).)

**Comment by dmey** [comment]
@EmmEff is this actually coming from the Singularity on the [remote builder](https://cloud.sylabs.io/builder)? If that's the case is there an ETA for this fix?

**Comment by jscook2345** [comment]
@dmey 

Are you building with the same definition? Could you share your build command so I could try to reproduce?

**Comment by dmey** [comment]
> Are you building with the same definition

What do you mean exactly? Same as in [README.md](https://github.com/sylabs/singularity/blob/master/INSTALL.md#compiling-singularity)? If so, yes.

>Could you share your build command so I could try to reproduce?
```
mkdir -p ${GOPATH}/src/github.com/sylabs && \
  cd ${GOPATH}/src/github.com/sylabs && \
  git clone https://github.com/sylabs/singularity.git && \
  cd singularity

cd ${GOPATH}/src/github.com/sylabs/singularity && \
  ./mconfig && \
  cd ./builddir && \
  make && \
  sudo make install
```

**Comment by jscook2345** [comment]
@dmey 

Sorry, I meant your `singularity build` command. What commands are resulting in the above stack trace? And can you share the definition file used, if possible?

**Comment by dmey** [comment]
@jscook2345 
>What commands are resulting in the above stack trace?

`singularity build --remote image.sif image.def`

> And can you share the definition file used, if possible?



Sure -- see [image.def.txt](https://github.com/sylabs/singularity/files/3617233/image.def.txt).

**Comment by dtrudg** [comment]
Sorry about the confusion @dmey - with it clear that this is a remote build, yes the error is occurring in the remote builder in the cloud, not on your system.

@EmmEff - is the builder going to  / has been updated?

**Comment by hassanfa** [comment]
I have also encountered same issue. Both of my remote build and online building failed with same error. It worked just fine on singularity hub.

**Comment by dtrudg** [comment]
> Both of my remote build and online building

Hi @hassanfa - when you say 'online building' what `singularity build ...` command are you running, and what is the container that you are building? Thanks,

**Comment by hassanfa** [comment]
David,

I meant on sylabs's cloud: https://cloud.sylabs.io/builder for online. And for remote build, I meant using CLI. Apologies for not being clear.

**Comment by bgbrink** [comment]
I just wanted to check whether there is a temporary workaround until this is fixed?

**Comment by hassanfa** [comment]
For now I am keeping my containers under 1GB. Other than that, I have not found any solution yet.

**Comment by EmmEff** [comment]
This issue should now be resolved.

@bgbrink please retry and let us know. Thanks!
