### ISSUE TITLE
SIGABRT causes incorrect return code and stack trace

### ISSUE THREAD

**Issue by jjhursey** [apptainer/singularity#4706]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.4.0-1.2.el7
```

### Expected behavior

Two example programs below.

`foo.sh` returns `134` which is `SIGABRT` (`128+6`)
```
shell $ cat foo.sh 
#!/bin/bash
exit 134
```
`bar.sh` returns `136` which is `SIGFPE` (`128+8`)
```
shell $ cat bar.sh 
#!/bin/bash
exit 136
```

Running these programs outside of the container looks like:
```
shell $ ./foo.sh 
shell $ echo $?
134
shell $ ./bar.sh 
shell $ echo $?
136
```

I would expect the same behavior when running these programs inside of a Singularity container.

### Actual behavior

For `bar.sh` this works correctly.
```
shell $ ./bar.sh 
shell $ echo $?
136
shell $ singularity exec -i docker://ppc64le/centos:7 ~/bar.sh 
shell $ echo $?
136
```

However, for `foo.sh`, when a program exits with `SIGABRT` (`134`) Singularity dumps a stack and returns an incorrect return code.

```
shell $ ./foo.sh 
shell $ echo $?
134
shell $ singularity exec -i docker://ppc64le/centos:7 ~/foo.sh 
SIGABRT: abort
PC=0x10071324 m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x25, 0x331f, 0x6, 0x0, 0x0, 0xc00000c480, 0x331f)
	/usr/lib/golang/src/syscall/asm_linux_ppc64x.s:71 +0x24 fp=0xc00034de48 sp=0xc00034de48 pc=0x10071324
syscall.Kill(0x331f, 0x6, 0x10a53bbc, 0x100094dc)
	/usr/lib/golang/src/syscall/zsyscall_linux_ppc64le.go:597 +0x40 fp=0xc00034dea0 sp=0xc00034de48 pc=0x1006dc70
github.com/sylabs/singularity/internal/app/starter.Master.func2()
	internal/app/starter/master_linux.go:152 +0x3c fp=0xc00034dee8 sp=0xc00034dea0 pc=0x102f12ac
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
	internal/pkg/util/mainthread/mainthread.go:21 +0x38 fp=0xc00034df20 sp=0xc00034dee8 pc=0x102efda8
main.main()
	cmd/starter/main_linux.go:102 +0x5c fp=0xc00034df68 sp=0xc00034df20 pc=0x104a4d8c
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:201 +0x214 fp=0xc00034dfc0 sp=0xc00034df68 pc=0x100308e4
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_ppc64x.s:784 +0x4 fp=0xc00034dfc0 sp=0xc00034dfc0 pc=0x1005bec4

goroutine 5 [syscall]:
os/signal.signal_recv(0x10692740)
	/usr/lib/golang/src/runtime/sigqueue.go:139 +0xfc
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:23 +0x24
created by os/signal.init.0
	/usr/lib/golang/src/os/signal/signal_unix.go:29 +0x3c

goroutine 7 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc0002a4a10)
	internal/pkg/util/mainthread/mainthread.go:24 +0xa8
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x4, 0x3343, 0xc00000eb40)
	internal/app/starter/master_linux.go:151 +0x354
main.startup()
	cmd/starter/main_linux.go:75 +0x450
created by main.main
	cmd/starter/main_linux.go:98 +0x34

r0   0x25	r1   0xc00034de48
r2   0x10009654	r3   0x0
r4   0x6	r5   0x0
r6   0x0	r7   0x0
r8   0x0	r9   0x0
r10  0x0	r11  0x0
r12  0x0	r13  0x3fff87bdb360
r14  0xc	r15  0x10686f6e
r16  0x3000	r17  0x3000
r18  0x0	r19  0x10686f6c
r20  0xc000026e28	r21  0xc00000c480
r22  0x0	r23  0x0
r24  0x3fff85630626	r25  0xb0
r26  0x0	r27  0x3fff87bcfbb8
r28  0x3fff87bd0000	r29  0x3fff87bcf550
r30  0xc000000180	r31  0x102f12ac
pc   0x10071324	ctr  0x0
link 0x1006dc70	xer  0x0
ccr  0x44400402	trap 0xc00
shell $ echo $?
2
```

### Steps to reproduce this behavior

See above for reproducer.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```

### How did you install Singularity

Singularity installed from EPEL RPM `singularity-3.4.0-1.2.el7.ppc64le`

**Comment by dtrudg** [comment]
Ref: https://akutz.wordpress.com/2017/10/02/golang-and-sigabrt/

> Golang programs interpret the SIGABRT signal as a special event that forces a core dump, including all goroutines and if they’re deadlocked.

**Comment by jjhursey** [comment]
I figured that was what was going on. Is there any way to disable it? Otherwise, this seems like a restriction to document.

**Comment by dtrudg** [comment]
@jjhursey - in theory it looks like we can install a SIGABRT handler to override this, but we'll have to have some discussion about it. I do agree that it's not great that the behavior varies from running the same outside of the container.
