### ISSUE TITLE
Can't start singularity

### ISSUE THREAD

**Issue by soichih** [apptainer/singularity#5329]
I am using singularity version 3.5.2

I started seeing the following error message when I try to run singularity (with any docker container)

```
singularity exec -e docker://brainlife/dipy:1.1.1 python --version
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 5c939e3a4d10 [--------------------------------------] 0b / 0b
Copying blob c63719cdbe7a [--------------------------------------] 0b / 0b
Copying blob 19a861ea6baf [--------------------------------------] 0b / 0b
Copying blob 651c9d2d6c4f [--------------------------------------] 0b / 0b
Copying blob 5eb8dd98bb59 [--------------------------------------] 0b / 0b
Copying blob dacc12582d2a [--------------------------------------] 0b / 0b
Copying blob c2b39268fcc4 [--------------------------------------] 0b / 0b
Copying blob 8eb443804c29 [--------------------------------------] 0b / 0b
panic: page 57 already freed

goroutine 175 [running]:
github.com/etcd-io/bbolt.(*freelist).free(0xc000571380, 0x460, 0x2af751da7000)
	github.com/etcd-io/bbolt@v1.3.3/freelist.go:175 +0x3d4
github.com/etcd-io/bbolt.(*node).spill(0xc00046a380, 0xc00037c0e0, 0x1)
	github.com/etcd-io/bbolt@v1.3.3/node.go:363 +0x206
github.com/etcd-io/bbolt.(*node).spill(0xc00046a310, 0xc000502960, 0x47)
	github.com/etcd-io/bbolt@v1.3.3/node.go:350 +0xba
github.com/etcd-io/bbolt.(*Bucket).spill(0xc0003e26c0, 0xc0003e0a00, 0xc00026d1d8)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:568 +0x473
github.com/etcd-io/bbolt.(*Bucket).spill(0xc0003e2680, 0xc00050d200, 0xc00026d3d0)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:535 +0x3d5
github.com/etcd-io/bbolt.(*Bucket).spill(0xc0003e2640, 0xc00050d000, 0xc00026d5c8)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:535 +0x3d5
github.com/etcd-io/bbolt.(*Bucket).spill(0xc0003b5b38, 0x6cac4bf5, 0x1ecb360)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:535 +0x3d5
github.com/etcd-io/bbolt.(*Tx).Commit(0xc0003b5b20, 0x0, 0x0)
	github.com/etcd-io/bbolt@v1.3.3/tx.go:160 +0xec
github.com/etcd-io/bbolt.(*DB).Update(0xc00067c200, 0xc0002538c0, 0x0, 0x0)
	github.com/etcd-io/bbolt@v1.3.3/db.go:701 +0x106
github.com/containers/image/pkg/blobinfocache/boltdb.(*cache).update(0xc00035cd80, 0xc0002538c0, 0x0, 0x0)
	github.com/containers/image@v3.0.2+incompatible/pkg/blobinfocache/boltdb/boltdb.go:141 +0x147
github.com/containers/image/pkg/blobinfocache/boltdb.(*cache).RecordKnownLocation(0xc00035cd80, 0x15f5e00, 0x1ee9ec8, 0xc000514500, 0x9, 0xc000036aa0, 0x47, 0xc0005bdc40, 0x18)
	github.com/containers/image@v3.0.2+incompatible/pkg/blobinfocache/boltdb/boltdb.go:226 +0xcd
github.com/containers/image/docker.(*dockerImageSource).GetBlob(0xc000524200, 0x15fabc0, 0xc000040098, 0xc000036aa0, 0x47, 0x16f48e4, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/containers/image@v3.0.2+incompatible/docker/docker_image_src.go:239 +0x484
github.com/containers/image/copy.(*imageCopier).copyLayer(0xc00020c390, 0x15fabc0, 0xc000040098, 0xc000036aa0, 0x47, 0x16f48e4, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/containers/image@v3.0.2+incompatible/copy/copy.go:690 +0x16b
github.com/containers/image/copy.(*imageCopier).copyLayers.func1(0x8, 0xc000036aa0, 0x47, 0x16f48e4, 0x0, 0x0, 0x0, 0x0, 0xc000369900, 0x31, ...)
	github.com/containers/image@v3.0.2+incompatible/copy/copy.go:486 +0x4a6
created by github.com/containers/image/copy.(*imageCopier).copyLayers.func2
	github.com/containers/image@v3.0.2+incompatible/copy/copy.go:497 +0x204
```

I've cleared the cache directory (pointed by SINGULARITY_CACHEDIR) but the problem persists. How can I resolve this?

**Comment by dtrudg** [comment]
Something is very strange here, and it's occurring in a library Singularity uses to handle docker/OCI images, not Singularity's code itself.

Looking through this, the issue seems to occur where boltdb is used on a filesystem that is not supported.

What Linux version are you running, and what filesystem is your `SINGULARITY_CACHEDIR` on, and your `TMPDIR` on?

Could you provide output of `mount` or mount options.

Thanks.

**Comment by soichih** [comment]
```
SINGULARITY_CACHEDIR=/N/dc2/scratch/brlife/singularity-cache-carb
```

TMPDIR is not set when I tested it locally, but I ran into the same issue if I submit a job through PBS scheduler which set it to something like `TMPDIR=/tmp/1828768.s1`

/N/dc2 is listed in the bind path on singularity.conf
```
bind path = /etc/localtime
bind path = /etc/hosts
bind path = /N/home
bind path = /N/u
bind path = /N/dc2
bind path = /N/soft
bind path = /N/dcwan
```

and it is a lustre filesystem.

```
rlife@carbonate(h1):/N/dc2 $ df -T .
Filesystem                             Type       1K-blocks          Used    Available Use% Mounted on
10.10.0.171@o2ib:10.10.0.172@o2ib:/dc2 lustre 5724702779040 5144821500116 521607799932  91% /N/dc2
```

I don't know of any changes made to how /dc2 is mounted, and it seems to work fine on other clusters (bigred3) that are using dc2 for SINGULARITY_CACHEDIR.

Thanks @dctrud

**Comment by dtrudg** [comment]
Can you provide the `mount` output for the machine(s) where there is an issue, and where there is not?

The `df` doesn't show the mount options, and it's possible that there is a difference between the locking options on the lustre mount etc.

Thanks.

**Comment by soichih** [comment]
Here is the mount output on carbonate (where I am having this problem)

```
brlife@carbonate(h1):~ 2 mount
sysfs on /sys type sysfs (rw,relatime)
proc on /proc type proc (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=131697540k,nr_inodes=32924385,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_prio,net_cls)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
configfs on /sys/kernel/config type configfs (rw,relatime)
rootfs on / type tmpfs (rw,relatime,mode=755)
rw on /.sllocal/log type tmpfs (rw,relatime)
rpc_pipefs on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=136383)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
/dev/sda1 on /var type ext4 (rw,relatime,data=ordered)
/dev/sda2 on /tmp type ext4 (rw,relatime,data=ordered)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=26343784k,mode=700)
g2-soft on /geode2/soft type gpfs (rw,relatime)
g2-home on /geode2/home type gpfs (rw,relatime)
g2-logs on /geode2/logs type gpfs (rw,relatime)
g2-projects on /geode2/projects type gpfs (rw,relatime)
10.10.0.171@o2ib:10.10.0.172@o2ib:/dc2 on /N/dc2 type lustre (rw,flock,lazystatfs)
149.165.235.43@tcp:/dcwan2 on /N/dcwan type lustre (rw,flock,lazystatfs)
10.10.4.201@o2ib:10.10.4.202@o2ib:/condo on /N/project type lustre (rw,flock,lazystatfs)
10.10.2.201@o2ib:10.10.2.202@o2ib:/slate on /N/slate type lustre (rw,flock,lazystatfs)
tmpfs on /run/user/1652535 type tmpfs
...
```

and on bigred3 (where everything still works)

```
brlife@elogin2:~> mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,noexec,size=131943140k,nr_inodes=32985785,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,noexec)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,mode=755)
overlay on / type overlay (rw,relatime,lowerdir=/tmp/os,upperdir=/tmp/writeable/overlay,workdir=/tmp/writeable/work)
/dev/sda2 on /boot type ext3 (rw,relatime,data=ordered)
/dev/sdb1 on /var/crash type ext4 (rw,relatime,data=ordered)
/dev/sda4 on /tmp type tmpfs (rw,relatime)
/dev/sdb2 on /var/opt/cray/persistent type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdb2 on /var/opt/cray/imps/config/sets type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sdb2 on /cray_home type xfs (rw,relatime,attr2,inode64,noquota)
/dev/sda4 on /tmp type tmpfs (rw,relatime)
rpc_pipefs on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
tmpfs on /var/run type tmpfs (rw,nosuid,nodev,noexec,mode=755)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/sda4 on /tmp type tmpfs (rw,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /var/opt/cray/imps-image-binding/PE/squash_mounts/squashfs_TgOLwr_mount_point type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /etc/opt/cray/pe type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /opt/R type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /opt/admin-pe type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /opt/cray/pe type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /opt/jemalloc type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /opt/python type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /opt/gcc type squashfs (ro,relatime)
/var/opt/cray/persistent/image_roots/pe_compute_cle_6.0up06_sles_12sp3/squashfs on /opt/java type squashfs (ro,relatime)
149.165.235.43@tcp:/dcwan2 on /N/dcwan type lustre (rw,flock,lazystatfs)
10.10.0.171@o2ib:10.10.0.172@o2ib:/dc2 on /N/dc2 type lustre (rw,flock,lazystatfs)
10.10.2.201@o2ib:10.10.2.202@o2ib:/slate on /N/slate type lustre (rw,flock,lazystatfs)
10.10.4.201@o2ib:10.10.4.202@o2ib:/condo on /N/project type lustre (rw,flock,lazystatfs)
/dev/sdb2 on /var/mmfs type xfs (rw,relatime,attr2,inode64,noquota)
g2-home on /geode2/home type gpfs (rw,relatime)
g2-soft on /geode2/soft type gpfs (rw,relatime)
g2-logs on /geode2/logs type gpfs (rw,relatime)
g2-projects on /geode2/projects type gpfs (rw,relatime)
/dev/sdb2 on /var/log/audit type xfs (rw,relatime,attr2,inode64,noquota)
tmpfs on /run/user/5366 type tmpfs (rw,nosuid,nodev,relatime,size=26392952k,mode=700,uid=5366,gid=42999)
tmpfs on /var/run/user/5366 type tmpfs (rw,nosuid,nodev,relatime,size=26392952k,mode=700,uid=5366,gid=42999)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
...
```

Both seems to be using the identical options? 

bigred3 is SLES 12 SP3, and using the following kernel
> Linux elogin2 4.4.180-94.113-default #1 SMP Fri Dec 13 14:20:57 UTC 2019 (c6649f6) x86_64 x86_64 x86_64 GNU/Linux
> singularity version 3.5.2+206-gcf7fad2f4

carbonate is RHEL7.7 with the following kernel
> Linux h1.carbonate.uits.iu.edu 3.10.0-1062.12.1.el7.x86_64 #1 SMP Thu Dec 12 06:44:49 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
> singularity version 3.5.2

By the way, I don't think this is related to dc2/lustre. If I point the CACHEDIR to my local /tmp directory (/dev/sda2 on /tmp type ext4 (rw,relatime,data=ordered))

> export SINGULARITY_CACHEDIR=/tmp/soichi

I ran into the same problem..

```
brlife@carbonate(h1):~ 2 singularity exec -e docker://busybox whoami
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
panic: page 57 already freed

goroutine 205 [running]:
github.com/etcd-io/bbolt.(*freelist).free(0xc000710480, 0x460, 0x2b515ff75000)
	github.com/etcd-io/bbolt@v1.3.3/freelist.go:175 +0x3d4

```

**Comment by dtrudg** [comment]
Okay, thanks, we're getting closer. Please could you provide the full debug output from `singularity -d ...` for the command that is failing? Also the output of `singularity buildcfg`.

If it's occurring when we are definitely doing things on `/tmp`, which is a local ext4 partition on the carbonate system then it's a puzzle to me.

These bolt page already freed panics do come up in various other container related projects, using some of the libraries that Singularity is. Mostly it is fs related. I am not able to replicate this on a local RHEL 7.7 system yet.

**Comment by soichih** [comment]
Here is the output with -d option set

```
brlife@carbonate(h1):~ $ export SINGULARITY_CACHEDIR=/tmp/soichi
brlife@carbonate(h1):~ $ singularity -d exec -e docker://busybox whoami
DEBUG   [U=1589653,P=27653]persistentPreRunE()           Singularity version: 3.5.2
DEBUG   [U=1589653,P=27653]handleConfDir()               /N/u/brlife/Carbonate/.singularity already exists. Not creating.
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/library
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/oci-tmp
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/oci
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/net
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/shub
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/oras
DEBUG   [U=1589653,P=27653]parseURI()                    Parsing docker://busybox into reference
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/oci-tmp/836945da1f3afe2cfff376d379852bbb82e0237cb2925d53a13f53d6e8a8c48c
DEBUG   [U=1589653,P=27653]updateCacheSubdir()           Caching directory set to /tmp/soichi/cache/oci-tmp/836945da1f3afe2cfff376d379852bbb82e0237cb2925d53a13f53d6e8a8c48c
INFO    [U=1589653,P=27653]handleOCI()                   Converting OCI blobs to SIF format
DEBUG   [U=1589653,P=27653]newBundle()                   Created temporary directory "/tmp/bundle-temp-602597868" for the bundle
DEBUG   [U=1589653,P=27653]newBundle()                   Created directory "/tmp/rootfs-510567b9-a430-11ea-84de-42f2e9c677b7" for the bundle
DEBUG   [U=1589653,P=27653]ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=1589653,P=27653]ensureGzipComp()              Gzip compression by default ensured
INFO    [U=1589653,P=27653]Full()                        Starting build...
DEBUG   [U=1589653,P=27653]Get()                         Reference: busybox
Getting image source signatures
panic: page 57 already freed

goroutine 117 [running]:
github.com/etcd-io/bbolt.(*freelist).free(0xc000660400, 0x460, 0x2b4261a46000)
	github.com/etcd-io/bbolt@v1.3.3/freelist.go:175 +0x3d4
github.com/etcd-io/bbolt.(*node).spill(0xc0002ca540, 0xc000538a40, 0x1)
	github.com/etcd-io/bbolt@v1.3.3/node.go:363 +0x206
github.com/etcd-io/bbolt.(*node).spill(0xc0002ca4d0, 0xc000536730, 0x47)
	github.com/etcd-io/bbolt@v1.3.3/node.go:350 +0xba
github.com/etcd-io/bbolt.(*Bucket).spill(0xc000514380, 0xc000545800, 0xc0002451d8)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:568 +0x473
github.com/etcd-io/bbolt.(*Bucket).spill(0xc000514340, 0xc000545000, 0xc0002453d0)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:535 +0x3d5
github.com/etcd-io/bbolt.(*Bucket).spill(0xc000514300, 0xc000544e00, 0xc0002455c8)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:535 +0x3d5
github.com/etcd-io/bbolt.(*Bucket).spill(0xc0003a27f8, 0x6f1352e0, 0x1ecb360)
	github.com/etcd-io/bbolt@v1.3.3/bucket.go:535 +0x3d5
github.com/etcd-io/bbolt.(*Tx).Commit(0xc0003a27e0, 0x0, 0x0)
	github.com/etcd-io/bbolt@v1.3.3/tx.go:160 +0xec
github.com/etcd-io/bbolt.(*DB).Update(0xc0005c4400, 0xc0002218c0, 0x0, 0x0)
	github.com/etcd-io/bbolt@v1.3.3/db.go:701 +0x106
github.com/containers/image/pkg/blobinfocache/boltdb.(*cache).update(0xc0006da0c0, 0xc0002218c0, 0x0, 0x0)
	github.com/containers/image@v3.0.2+incompatible/pkg/blobinfocache/boltdb/boltdb.go:141 +0x147
github.com/containers/image/pkg/blobinfocache/boltdb.(*cache).RecordKnownLocation(0xc0006da0c0, 0x15f5e00, 0x1ee9ec8, 0xc000512920, 0x9, 0xc0005360a0, 0x47, 0xc0002687c0, 0x19)
	github.com/containers/image@v3.0.2+incompatible/pkg/blobinfocache/boltdb/boltdb.go:226 +0xcd
github.com/containers/image/docker.(*dockerImageSource).GetBlob(0xc0004221c0, 0x15fabc0, 0xc000040098, 0xc0005360a0, 0x47, 0xb9c0f, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/containers/image@v3.0.2+incompatible/docker/docker_image_src.go:239 +0x484
github.com/containers/image/copy.(*imageCopier).copyLayer(0xc0003e1dd0, 0x15fabc0, 0xc000040098, 0xc0005360a0, 0x47, 0xb9c0f, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/containers/image@v3.0.2+incompatible/copy/copy.go:690 +0x16b
github.com/containers/image/copy.(*imageCopier).copyLayers.func1(0x0, 0xc0005360a0, 0x47, 0xb9c0f, 0x0, 0x0, 0x0, 0x0, 0xc0005d21c0, 0x31, ...)
	github.com/containers/image@v3.0.2+incompatible/copy/copy.go:486 +0x4a6
created by github.com/containers/image/copy.(*imageCopier).copyLayers.func2
	github.com/containers/image@v3.0.2+incompatible/copy/copy.go:497 +0x204

```

```
$ singularity buildcfg
PACKAGE_NAME=singularity
PACKAGE_VERSION=3.5.2
BUILDDIR=/home/build/src/singularity-3.5.2/builddir
PREFIX=/N/soft/rhel7/singularity/3.5.2
EXECPREFIX=/N/soft/rhel7/singularity/3.5.2
BINDIR=/N/soft/rhel7/singularity/3.5.2/bin
SBINDIR=/N/soft/rhel7/singularity/3.5.2/sbin
LIBEXECDIR=/N/soft/rhel7/singularity/3.5.2/libexec
DATAROOTDIR=/N/soft/rhel7/singularity/3.5.2/share
DATADIR=/N/soft/rhel7/singularity/3.5.2/share
SYSCONFDIR=/N/soft/rhel7/singularity/3.5.2/etc
SHAREDSTATEDIR=/N/soft/rhel7/singularity/3.5.2/com
LOCALSTATEDIR=/N/soft/rhel7/singularity/3.5.2/var
RUNSTATEDIR=/N/soft/rhel7/singularity/3.5.2/var/run
INCLUDEDIR=/N/soft/rhel7/singularity/3.5.2/include
DOCDIR=/N/soft/rhel7/singularity/3.5.2/share/doc/singularity
INFODIR=/N/soft/rhel7/singularity/3.5.2/share/info
LIBDIR=/N/soft/rhel7/singularity/3.5.2/lib
LOCALEDIR=/N/soft/rhel7/singularity/3.5.2/share/locale
MANDIR=/N/soft/rhel7/singularity/3.5.2/share/man
SINGULARITY_CONFDIR=/N/soft/rhel7/singularity/3.5.2/etc/singularity
SESSIONDIR=/N/soft/rhel7/singularity/3.5.2/var/singularity/mnt/session

```

**Comment by soichih** [comment]
@dctrud 

I've noticed that, singularity works fine on a different user account (with a bit more administrative access than the brlife user that I was using). So this issue is user ID specific.

Also, I saw this output while looking through strace output

```
openat(AT_FDCWD, "/etc/pki/tls/certs/ca-bundle.crt", O_RDONLY|O_CLOEXEC) = 7
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=1412146232, u64=47409261159480}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 7, 0xc00036b16c) = -1 EPERM (Operation not permitted)
```

I can just cat fine with this file..

```
$ cat /etc/pki/tls/certs/ca-bundle.crt
... (usual stuff here)
```

So I am not sure what "Operations not permitted" means, but on my other account (that works) stract doesn't even show it's accessing this file. So I am not sure why it's trying to access this file.

Just FYI

**Comment by dtrudg** [comment]
I don't believe the EPOLL stuff here is anything that would cause a problem.

Here's something to try....

Check for a file under: `$HOME/.local/share/containers/cache/` - that should be named something like `blob-info-cache-v1.boltdb`

If you find one, remove it.

This is the boltdb database the `containers/image` library is using to cache information about OCI/Docker blobs (layers & manifests).

I suspect it has become corrupt.

**Comment by soichih** [comment]
That fixed it!

```
brlife@carbonate(h1):~/.local/share/containers/cache $ mv blob-info-cache-v1.boltdb  ~/
brlife@carbonate(h1):~/.local/share/containers/cache $ cd
brlife@carbonate(h1):~ $ singularity exec -e docker://busybox whoami
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob d9cbbca60e5f done
Copying config 8f5af4048c done
Writing manifest to image destination
Storing signatures
2020/06/02 11:24:56  info unpack layer: sha256:d9cbbca60e5f0fc028b13c01e70e96cc2eefe7858ccc5a33c9a8faa8b03286aa
INFO:    Creating SIF file...
brlife
```

**Comment by dtrudg** [comment]
Good to know!

This file would be shared by anything using the `containers/xxxx` libraries like the Red Hat podman / skopeo / buildah tools - so we shouldn't make `singularity cache clean` wipe it (though that would allow cache clean to fix this issue).

There seems to be some disagreement around on the net about whether or not boltdb is properly safe on shared filesystems. We haven't had any other reports of this issue, but we'll keep an eye on it.

**Comment by ionox0** [comment]
just noting that I've experienced this same error on singularity 3.7.1

removing the boltdb file also fixed it in this case

**Comment by stevekm** [comment]
I also had this issue on singularity 3.7.1, after the home directory ran out of space 

seems like the boltdb file got corrupted after a failed Singularity operation due to lack of space in the home dir

**Comment by soichih** [comment]
We keep running into this issue. (singularity 3.7.2)

Removing `blob-info-cache-v1.boltdb` seems to temporarily cure the symptom, but after days/weeks or operation, the same issue reoccurs. On our HPC system, our home directories are configured to use the shared GPFS amount, and all compute nodes shares the same shared home directory. My guess is that, when multiple jobs are started and all of them simultaneously tries to cache SIF image, something goes bad and ends up with corrupted `blob-info-cache-v1.boltd` file? Is there a way to enforce some type of flock?

**Comment by DrDaveD** [comment]
@soichih Please create a new apptainer/apptainer issue for this, referring back to this one.

Very likely a fix would have to be done in the dependent package, but we could track it there.

**Comment by soichih** [comment]
Will do!
