### ISSUE TITLE
building without directory bindings

### ISSUE THREAD

**Issue by onurkulak** [apptainer/singularity#5523]
I have a problem/question about home directory bindings. I don't want them but during build stage my container creates some files in the local builder's home directory. And then the container complains when I move and run it on the hpc because of these files installed on my local computer. 

I want to be able to run this container smoothly in other machines without worrying about the bonded files etc. How do I do that? there is no 'no-home' like flag during build stage afaik. I want these files to be bundled with my container rather than existing in the host computer.

### Version of Singularity:

What version of Singularity are you using? Run:

```
3.5.3

```

### Expected behavior

program running flawlessly, output on my laptop
```
onurkulaksizoglu@pop-os:~/work/actorsim-sim-malmo/malmo-singularity$ singularity run --writable malmo.sif 
Entering daemon mode; any further errors will be reported to:
  /home/onurkulaksizoglu/.xpra/:100.log
This mapping 'snapshot_20161220' was designed for MC 1.11! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-3966cea        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:genSrgs SKIPPED
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:deobfMcSRG SKIPPED
:decompileMc SKIPPED
:fixMcSources
Patching failed: minecraft\net\minecraft\util\math\Cartesian.java
...
```

### Actual behavior

output on the hpc gives error about home directory bindings which I don't want/care at all, (I couldn't replicate the same error I got previously but they are all similar binding errors).
I am also getting this warning from the hpc and I don't know what does it imply:
`[33mWARNING:[0m Bind mount '/homes/kulaksor => /homes/kulaksor' overlaps container CWD /homes/kulaksor/lustre/malmo-singularity, may not be available`

when I try to run with --no-home flag then I get errors about some files not existing in the home directory.
```
singularity run --writable --no-home malmo.sif 

xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/xpra/scripts/main.py", line 130, in main
    return run_mode(script_file, err, options, args, mode, defaults)
  File "/usr/lib/python2.7/dist-packages/xpra/scripts/main.py", line 871, in run_mode
    return run_server(error_cb, options, mode, script_file, args)
  File "/usr/lib/python2.7/dist-packages/xpra/scripts/server.py", line 744, in run_server
    dotxpra = DotXpra(opts.socket_dir)
  File "/usr/lib/python2.7/dist-packages/xpra/dotxpra.py", line 32, in __init__
    os.mkdir(self._confdir, 0o700)
OSError: [Errno 30] Read-only file system: '/homes/kulaksor/.xpra'

Exception in thread "main" java.io.FileNotFoundException: /homes/kulaksor/.gradle/wrapper/dists/gradle-2.14-bin/76oc0mnc3ieqtsukq90mp0rxk/gradle-2.14-bin.zip.lck (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception in thread "main" java.io.FileNotFoundException: /homes/kulaksor/.gradle/wrapper/dists/gradle-2.14-bin/76oc0mnc3ieqtsukq90mp0rxk/gradle-2.14-bin.zip.lck (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception in thread "main" java.io.FileNotFoundException: /homes/kulaksor/.gradle/wrapper/dists/gradle-2.14-bin/76oc0mnc3ieqtsukq90mp0rxk/gradle-2.14-bin.zip.lck (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

```

**Comment by dtrudg** [comment]
Closing, as this issue is a usage question that has not had follow up for >90 days.

For issues that are questions r.e. using Singularity, rather than bugs or feature requests, the mailing-list and slack channel are often better venues. Questions to the slack channel and mailing list will be seen by a large number of subscribed users, rather than only those who look inside a particular GitHub issue. Therefore they are encouraged for this type of inquiry.

Slack: See https://hpcng.org/ for invite (bottom of page)
Mailing List / Google Group: https://groups.google.com/a/lbl.gov/forum/#!forum/singularity
