### ISSUE TITLE
guidelines for creating readonly docker containers compatible with singularity

### ISSUE THREAD

**Issue by satra** [apptainer/singularity#571]
since docker has the ability to overwrite files within the container, we are running into weird issues that would benefit from better container creation. turns out certain python pieces want to write things in some underlying hidden files, and if those things were not cleaned up during the container build process, singularity runs into an error, since everything is read-only.

are there any guidelines we can create that would support better container creation/testing between singularity and docker? for example, now i plan to go and make sure there is a line to remove these `.wh` files from the conda directory.

```
inside singularity container derived from docker> nipypecli 
Traceback (most recent call last):
  File "/opt/conda/bin/nipypecli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1873, in get_metadata_lines
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1861, in get_metadata
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.5/site-packages/.wh.nilearn-0.2.5-py3.5.egg-info'
```

**Comment by chrisgorgo** [comment]
We have been using the --read-only flag for docker run to test this.
Unfortunately, this flag is ignored on some Docker implementation (for
example the one on CircleCI).

**Comment by gmkurtzer** [comment]
I'm not positive I follow the issue, but even if the container isn't read only, I would hope the path to anywhere under `/opt/` is in fact read-only to non-root users.

**Comment by satra** [comment]
@gmkurtzer - it's the python process that tries to rewrite these files. however, docker allows rewrite without the `--read-only` flag, while in singularity i have to go and delete them, before i run anything. in some sense it's weird that it allows me to delete them.

```
Singularity workshops:latest-nofsspm:/home/satra> nipypecli
Traceback (most recent call last):
  File "/opt/conda/bin/nipypecli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1873, in get_metadata_lines
  File "/opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1861, in get_metadata
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.5/site-packages/.wh.nilearn-0.2.5-py3.5.egg-info'

Singularity workshops:latest-nofsspm:/home/satra> find /opt/conda/ -name ".wh*" | xargs rm -f

Singularity workshops:latest-nofsspm:/home/satra> nipypecli
Usage: nipypecli [OPTIONS] COMMAND [ARGS]...

Options:
  -h, --help  Show this message and exit.

Commands:
  convert  Export nipype interfaces to other formats.
  crash    Display Nipype crash files.
  run      Run a Nipype Interface.
  search   Search for tracebacks content.
  show     Print the content of Nipype node .pklz file.
```

**Comment by gmkurtzer** [comment]
How are you deleting files in `/opt` as you? What are the permissions of those files and the directory? Is the container mounted as writable?

**Comment by satra** [comment]
```
$ singularity shell -c docker://nipype/workshops:latest-nofsspm
```
inside container
```
Singularity workshops:latest-nofsspm:/home/satra> nipypecli
Traceback (most recent call last):
...
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.5/site-packages/.wh.nilearn-0.2.5-py3.5.egg-info'

Singularity workshops:latest-nofsspm:/home/satra> ls -al /opt/conda/lib/python3.5/site-packages/.wh.nilearn-0.2.5-py3.5.egg-info
--w------- 1 satra gablab 0 Mar 25 17:34 /opt/conda/lib/python3.5/site-packages/.wh.nilearn-0.2.5-py3.5.egg-info

Singularity workshops:latest-nofsspm:/home/satra> whoami
satra
```

**Comment by gmkurtzer** [comment]
Ohhhhhhh... duhh, I totally missed that you aren't using an image. Because it is a Docker splat, yes, all of the files are owned by you.

@vsoch It seems to me that all files being written from the tar stream should be readable by owner. I can't imagine any such situation where that wouldn't be the case. Perhaps we should just fix that across the board instead?

**Comment by vsoch** [comment]
Right now I'm using the same algorithm that we had talked about over slack, [this section here](https://github.com/singularityware/singularity/blob/development/libexec/python/sutils.py#L320). I can change that to be whatever you like, although my main concern would be an operation over huge numbers of files is going to make it really slow.

**Comment by gmkurtzer** [comment]
@vsoch You are already doing the iteration over large numbers of files, right? Does changing the data make it that much slower?

**Comment by vsoch** [comment]
I haven't tried it, if I know the right mode to use, I can try it.

**Comment by chrisgorgo** [comment]
I just run into the same issue. Something funky is going on. Here is what I did.

1. I imported a docker image directly from docker hub: `singularity pull -s 15307 --name /home/groups/russpold/singularity_images/poldracklab_fmriprep_0.4.5.img docker://poldracklab/fmriprep:0.4.5`

2. When I tried to run it I got this error:
```
[chrisgor@sh-ln02 login! ~]$ /home/groups/russpold/singularity_images/poldracklab_fmriprep_0.4.5.img
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1873, in get_metadata_lines
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1861, in get_metadata
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info'
```
3. I looked at the problematic file. It has no permissions:
```
[chrisgor@sh-ln02 login! ~]$ singularity exec -c /home/groups/russpold/singularity_images/poldracklab_fmriprep_0.4.5.img ls -al /usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info
---------- 1 root root 0 Jun 12 12:52 /usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info
```
4. I tried to do the same thing in Docker. No errors:
```
PS C:\Users\filo> docker run -ti --rm --read-only --tmpfs /tmp --entrypoint=bash poldracklab/fmriprep:0.4.5
root@7fba7fdf5578:~/src/fmriprep# fmriprep
usage: fmriprep [-h] [-v]
                [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-s SESSION_ID] [-r RUN_ID] [-t TASK_ID] [--debug]
                [--nthreads NTHREADS] [--n_cpus NTHREADS]
                [--omp-nthreads OMP_NTHREADS] [--mem_mb MEM_MB]
                [--use-plugin USE_PLUGIN]
                [--ignore {fieldmaps,slicetiming} [{fieldmaps,slicetiming} ...]]
                [--bold2t1w-dof {6,9,12}]
                [--output-space {T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} [{T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} ...]]
                [--template {MNI152NLin2009cAsym}]
                [--output-grid-reference OUTPUT_GRID_REFERENCE]
                [--skull-strip-ants] [--no-skull-strip-ants] [--fmap-bspline]
                [--fmap-no-demean] [--no-freesurfer] [--no-submm-recon]
                [-w WORK_DIR] [--reports-only] [--write-graph]
                bids_dir output_dir {participant}
```
5. I looked at the problematic file in Docker. It's not there!
```
PS C:\Users\filo> docker run -ti --rm --read-only --tmpfs /tmp --entrypoint=ls poldracklab/fmriprep:0.4.5 -al /usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info
ls: cannot access '/usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info': No such file or directory
```

This file exists in the singualrity image, but does not in the docker image that the singularity image was created from. Very strange! I'll try doing the conversion using docker2singularity and report back

**Comment by chrisgorgo** [comment]
BTW this is singularity 2.3 on Sherlock2

**Comment by chrisgorgo** [comment]
I also tried removing the files like @satra did, but this is no longer possible
```
[chrisgor@sh-ln02 login! ~]$ singularity shell -w /home/groups/russpold/singularity_images/poldracklab_fmriprep_0.4.5.img
Singularity: Invoking an interactive shell within container...

Singularity poldracklab_fmriprep_0.4.5.img:~> chmod a=rw /usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info
chmod: changing permissions of '/usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info': Operation not permitted
Singularity poldracklab_fmriprep_0.4.5.img:~> rm -rf /usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info
rm: cannot remove '/usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info': Permission denied
```

**Comment by vsoch** [comment]
for writable you need sudo, so you would need to run:

```
sudo singularity shell -w /home/groups/russpold/singularity_images/poldracklab_fmriprep_0.4.5.img
```

and then remove the files. Wheel files have historically caused a lot of trouble, they are some sort of new package (akin to an egg). The reason you don't see wheels in Docker is because the package works to "unpack at a later time" [see docs here](http://wheel.readthedocs.io/en/latest/). The solutions I can think of, off the top of my head, would be to package the Docker images with the wheels already extracted, or just removed. Take a look at [usage here](https://wheel.readthedocs.io/en/latest/#usage) - it looks like you can control where they unpack to, so perhaps you could do a folder that could be mounted (with write) or I bet you could force them to install before actually running the scripts. Keep us updated on what you find!

**Comment by chrisgorgo** [comment]
Update: I performed the conversion with docker2singularity and it worked without problems. What is more the problematic file `/usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info` is not present in the image created by docker2singularity (which is consistent with the original docker image).

I am not sure why the two images behave so differently.

**Comment by yarikoptic** [comment]
So it sounds like @vsoch 's suggestion to guarantee that wheels are fully extracted right away is the correct one... I did wipe out two of those .wh.* files blindly, but didn't even try to run actual analysis (yet), so don't know if it works.

Let's ask wheel-guru @matthew-brett -- what those .wh*.egg-info files are exactly about?  how we could avoid having them while pip installing things within Dockerfile?

**Comment by satra** [comment]
and to add to yarik's question, why are these modified when running?

for neurodocker we now generate these types of output:

```
RUN conda create -y -q --name neuro python=3.6 \
        jupyter jupyterlab traits pandas matplotlib scikit-learn seaborn swig reprozip reprounzip \
    && conda clean -tipsy \
    && /bin/bash -c "source activate neuro \
        && pip install -q --no-cache-dir \
        https://github.com/nipy/nipype/tarball/master nilearn https://github.com/INCF/pybids/archive/master.zip datalad dipy nipy duecredit pymvpa2" \
    && find /opt/conda -name ".wh*" -exec rm {} +
```

**Comment by chrisgorgo** [comment]
@satra does this solve the problem with `wh` files? In my case the `wh` files are not present in the original docker image. Do you what triggers their generation?

PS sorry for the close/open issue noise

**Comment by satra** [comment]
@chrisfilo - in the situations, where i have seen this, it appears to work. 

what triggers there generation is our question out to matthew

**Comment by yarikoptic** [comment]
FWIW, `-exec rm {} +` == `--delete`, correct? @satra

**Comment by satra** [comment]
@yarikoptic - i guess so - ha! never used `--delete` :)

**Comment by vsoch** [comment]
If you guys need a smaller image to debug, I made one (and literally just try random stuff when I have free time, lol)

```
singularity pull docker://vanessa/fmriprep-debug
```
You technically can remove them, but it doesn't seem like an elegant solution. The commands I've been messing around with pertain to controlling **if** caching is enabled, and where, kind of like:

```
pip wheel --wheel-dir=/tmp -r requirements.txt
pip install --no-index --find-links=/tmp -r requirements.txt
```
but if it's the case that the base image already has them or some setting, we are in trouble. The next thing I was going to try is the different options for disabling binary packages and what not: https://pip.pypa.io/en/stable/reference/pip_wheel/

Stupid wheels, wheels are for wagon wheel pasta, not python!

**Comment by vsoch** [comment]
and +1, when we figure this out I am going to either figure out how to enforce it, or write it in **REALLY BIG** letters. Everywhere.

**Comment by vsoch** [comment]
![image](https://user-images.githubusercontent.com/814322/29056373-9c1a1d38-7bd0-11e7-8268-9a1c71c2c49a.png)

**Comment by matthew-brett** [comment]
Sorry - I have never seen these `.wh.nilearn-0.2.5-py3.5.egg-info` type files - maybe they are specific to Conda? (I don't use Conda)

**Comment by vsoch** [comment]
It's the new package format for python (think like an egg) http://wheel.readthedocs.io/en/latest/ and I think integrated with pip. Thus far I've only found them annoying, but probably there are some good use cases.

**Comment by matthew-brett** [comment]
Vanessa - is the contents of that directory really an unpacked wheel?  That would be very surprising to me, as far as I know Conda does not use wheels.

**Comment by satra** [comment]
@matthew-brett - the wheels are installed via pip inside a conda environment.

**Comment by matthew-brett** [comment]
Hum - I'd be very surprised if ".wh.nilearn-0.2.5-py3.5.egg-info" is a wheel directory.  

For example, if I pip install nipype now, I get these directories in `site-packages':

* `nipype-0.12.1.dist-info`
* `nipype`.

I don't get any `.wh` directories (and I have none in `site-packages`). I just checked installing Miniconda and then pip installing nipype - I still don't get any `.wh` directories.

In general, I believe that the `egg-info` directories are leftovers from setuptools installations - see [this SO link](https://stackoverflow.com/questions/256417/python-packages-and-egg-info-directories#256614).

**Comment by chrisgorgo** [comment]
Update:
Neither ` find /opt/conda -name ".wh*" -exec rm {} +` nor `conda clean -tipsy` nor running `fmriprep --version` in Dockerfile solved the issue for me.

However, I noticed that my error mentions `.wh.conda-4.3.11-py3.6.egg-info` file while the build logs indicate that conda has been updated to 4.3.23. When I forced conda to remain at the original version that it came with miniconda the `wh` file related error went away. Still not sure why.

**Comment by oesteban** [comment]
I think this is an interaction of docker build and conda. Please see https://github.com/poldracklab/fmriprep/pull/651#issuecomment-321108790

Long story sort: after every conda command a `sync` call is necessary.

**Comment by kaczmarj** [comment]
these `.wh.*` files are most likely aufs whiteout files, not artifacts of wheels. see moby/moby#9690 and specifically [this comment](https://github.com/moby/moby/issues/9690#issuecomment-76291959). that might explain why `sync` solves the issue.

**Comment by yarikoptic** [comment]
Wow... Great find @kaczmarj! And what a coincidence in naming - I thought wh was due to wheel ;-)

**Comment by vsoch** [comment]
ahhh so it's Docker's fault? This is very funny. What a find!!

**Comment by vsoch** [comment]
and here I was thinking of pasta....

... still thinking about pasta :-) 🍝

**Comment by justbennet** [comment]
Are you sure this is not a conda problem?  I had a similar issue with conda installing files with the wrong permissions when using it to update Anaconda.  Alas, Continuum pointed at Conda, who pointed back. Might conda itself be creating them to keep track of any wheels/pseudo-wheels that it might be employing?  In my case, I waited for a newer release and someone silently fixed the problem; I do not use conda to update any more.

Just thought I'd throw that in in case it's germane.

**Comment by satra** [comment]
@justbennet - we have not seen this error since we implemented the `sync` call

**Comment by justbennet** [comment]
Ah.  That's good to know.  Then should this issue be resolved?

**Comment by vsoch** [comment]
What does sync do under the hood?

If everyone is happy, we can close the issue. If this is a common issue, however, I might want to add it to the troubleshooting guide. Is this generally the case with singularity and conda, only within the context of docker (or anytime using anaconda)? And I assume the mini :snake: too?

**Comment by justbennet** [comment]
In the old days, sync forced any cached disk operations to be finalized;
so, writing and closing files, removing temporary files, etc.  Maybe there
is something else, but that's what I understood it to mean.  It seemed very
old school and made me wax nostalgic for a moment.

One always used to

   sync ; sync ; sync

before rebooting, for example.  (Twice to insure sucess, and once for luck.)

**Comment by vsoch** [comment]
awww :smile: :four_leaf_clover:

**Comment by gmkurtzer** [comment]
The good'ole days!

sync;sync;sync;sleep 5;reboot

**Comment by dtrudg** [comment]
Closing this as PRs fixing whiteout issues have been merged to development. Let us know if there are any remaining problems. Thanks!
