### ISSUE TITLE
Question: error from building singularity from *.def on ubuntu

### ISSUE THREAD

**Issue by Danissss** [apptainer/singularity#5740]
Since MacOS doesn't allow build singularity image from `*.def` (e.g. `singularity build singularity_con.img singularity_con.def`), I tried to build the image in ubuntu 20.04 but still get some issues.

Here is my def

```
Bootstrap: docker
Registry: docker://localhost:5000
Namespace:
From: singularity_con

%runscript
  cd /singularity_con
  bundle exec rake task:task
```

Here is the command I ran:
```
$ sudo singularity build singularity_con.sif singularity_con.def
```
Error:
```
Using container recipe deffile: classyfire_cc.def
Sanitizing environment
Adding base Singularity environment to container
Traceback (most recent call last):
  File "/usr/local/libexec/singularity/python/import.py", line 109, in <module>
    main()
  File "/usr/local/libexec/singularity/python/import.py", line 86, in main
    layerfile=LAYERFILE)
  File "/usr/local/libexec/singularity/python/docker/main.py", line 85, in IMPORT
    client = DockerApiConnection(image=image, auth=auth)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 92, in __init__
    self.load_image(kwargs['image'])
  File "/usr/local/libexec/singularity/python/docker/api.py", line 146, in load_image
    self.update_token()
  File "/usr/local/libexec/singularity/python/docker/api.py", line 191, in update_token
    response = self.get_tags(return_response=True)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 314, in get_tags
    return_response=return_response)
  File "/usr/local/libexec/singularity/python/base.py", line 291, in get
    updating_token=updating_token)
  File "/usr/local/libexec/singularity/python/base.py", line 310, in submit_request
    response = safe_urlopen(request)
  File "/usr/local/libexec/singularity/python/base.py", line 152, in safe_urlopen
    return opener.open(url, data=data)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727)>
Cleaning up...
```

Tried add `--nohttps`, but there is no `--nohttps` option in ubuntu singularity???

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
2.5.2-dist
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity

I installed the singularity through source 
```bash
git clone https://github.com/singularityware/singularity.git
cd singularity
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install
```
Thanks for help!

**Comment by dtrudg** [comment]
Singularity 2.x is no longer supported. Please use the latest 3.x version. No fixes or development have been made for 2.x for some time, and it was not tested on newer distributions such as Ubuntu 20.04, as it predates them.
