### ISSUE TITLE
Issue looking up hostname inside container

### ISSUE THREAD

**Issue by nordmoen** [apptainer/singularity#615]
After successfully creating a ROS Singularity container I'm having problem running ROS inside the container. Nodes in ROS speak over TCP connected through a [Master node](http://wiki.ros.org/Master) which orchestrates communication and it seems that this communication does not function properly inside a Singularity container.

I have tested with two different images, both of which compiles fine, but neither is able to run ROS. The best traceback I have been able to produce is this:
```bash
Singularity test.img:/workspace> roswtf
Loaded plugin tf.tfwtf
No package or stack in context
Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/roswtf", line 35, in <module>
    roswtf.roswtf_main()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/__init__.py", line 89, in roswtf_main
    _roswtf_main()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/__init__.py", line 175, in _roswtf_main
    roswtf.network.wtf_check(ctx)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/network.py", line 113, in wtf_check
    error_rule(r, r[0](ctx), ctx)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roswtf/network.py", line 51, in ip_check
    resolved_ips = [host[4][0] for host in socket.getaddrinfo(socket.gethostname(), 0, 0, 0, socket.SOL_TCP)]
socket.gaierror: [Errno -2] Name or service not known
```
Which comes from [`roswtf`](http://wiki.ros.org/roswtf), but all ROS nodes exhibit this problem. When trying to run [`roscore`](http://wiki.ros.org/roscore) I get the following:
```bash
Singularity test.img:/workspace> roscore -v
... logging to /home/jorgehn/.ros/log/02ed15b6-240f-11e7-88b9-e4a471879cef/roslaunch-jorgehn-x1-carbon-28202.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

... loading XML file [/opt/ros/kinetic/etc/ros/roscore.xml]
... executing command param [rosversion roslaunch]
Added parameter [/rosversion]
... executing command param [rosversion -d]
Added parameter [/rosdistro]
Added core node of type [rosout/rosout] in namespace [/]
Unable to contact my own server at [http://jorgehn-x1-carbon:42137/].
This usually means that the network is not configured properly.

A common cause is that the machine cannot ping itself.  Please check
for errors by running:

	ping jorgehn-x1-carbon

For more tips, please see

	http://www.ros.org/wiki/ROS/NetworkSetup

The traceback for the exception was written to the log file
```

The image I used to debug this is:
```bash
Bootstrap: docker
From: ros:kinetic

%setup
        # This is done before we are "inside" container

        # We first create our workspace folder
        mkdir -p $SINGULARITY_ROOTFS/workspace/src
        # Then copy our code into this workspace
        cd $SINGULARITY_ROOTFS/workspace/src
        git clone https://github.com/ros/ros_tutorials.git

%post
        # This is executed inside container
        . /opt/ros/kinetic/setup.sh
        cd /workspace/src
        catkin_init_workspace
        # Then it is time to build everything
        cd /workspace
        catkin_make
        catkin_make install

%runscript
        cd /workspace
        source /workspace/devel/setup.bash
```

The problem seem to be name resolution. I tried the following in Python inside the container:
```bash
Singularity test.img:/workspace> python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostname()
'jorgehn-x1-carbon'
>>> socket.getaddrinfo(socket.gethostname(), 0, 0, 0, socket.SOL_TCP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
>>> socket.getaddrinfo('127.0.0.1', 0, 0, 0, socket.SOL_TCP)
[(2, 1, 6, '', ('127.0.0.1', 0))]
```

**Comment by gmkurtzer** [comment]
Hi @nordmoen,

From a shell within that container image, what is in `/etc/resolv.conf`?

**Comment by nordmoen** [comment]
It seems to be the same as on my laptop:
```bash
Singularity test.img:~/Repos/singularity_images/dyret-map> cat /etc/resolv.conf 
# Generated by NetworkManager
search uio.no
nameserver 129.240.2.27
nameserver 129.240.2.40
nameserver 129.240.2.3
```

**Comment by gmkurtzer** [comment]
Do you have an entry for `jorgehn-x1-carbon` in the container's (or host's) `/etc/hosts`?

**Comment by nordmoen** [comment]
Neither the container nor the host have any reference to `jorgehn-x1-carbon` in their `/etc/hosts`.

Container `/etc/hosts`:
```bash
Singularity test.img:~/Repos/singularity_images/dyret-map> cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

```

**Comment by gmkurtzer** [comment]
Does that same python snippet work directly on your host?

```
$ cat <<EOF | python
import socket
socket.getaddrinfo(socket.gethostname(), 0, 0, 0, socket.SOL_TCP)
EOF
```

**Comment by nordmoen** [comment]
Yeah, the output is:
```bash
Python 2.7.13 (default, Jan 12 2017, 17:59:37) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo(socket.gethostname(), 0, 0, 0, socket.SOL_TCP)
[(10, 1, 6, '', ('fe80::4a5b:c553:f42b:a4dc%wlp4s0', 0, 0, 4)), (2, 1, 6, '', ('193.157.181.181', 0)), (2, 1, 6, '', ('192.168.122.1', 0)), (2, 1, 6, '', ('172.17.0.1', 0))]
>>> 
```

**Comment by gmkurtzer** [comment]
Very weird... I wonder if the glibc resolver on the host is acting differently then within the container. In either case, I would recommend adding an entry for the hostname of your system (`jorgehn-x1-carbon`) to your hosts `/etc/hosts` file for the IPv4 loopback address. And try again in your container.

Let me know if that helps!

**Comment by nordmoen** [comment]
Sorry for the long delay.

Adding `jorgehn-x1-carbon` to `/etc/hosts` works as expected.

**Comment by gmkurtzer** [comment]
Great news, thanks!
