### ISSUE TITLE
`urllib` module dependencies for Python 3

### ISSUE THREAD

**Issue by ashiklom** [apptainer/singularity#664]
The `docker` module will fail when using current Python 3 (which is the [default `python` executable on Arch Linux](https://wiki.archlinux.org/index.php/python), and it seems other distributions are [moving in this direction as well](https://wiki.ubuntu.com/Python)) with the following error:

```
Traceback (most recent call last):
  File "/usr/libexec/singularity/python/cli.py", line 27, in <module>
    from docker.api import get_layer, create_runscript, get_manifest, get_config, get_images
  File "/usr/libexec/singularity/python/docker/api.py", line 29, in <module>
    from utils import api_get, write_file, add_http
  File "/usr/libexec/singularity/python/utils.py", line 32, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

This is because the `urllib2` module has been [deprecated in Python 3](https://docs.python.org/2/library/urllib2.html).

Fortunately, this is easily fixed by running `2to3` on the `/usr/libexec/singularity/utils.py` script. I've provided the diff output from `2to3 utils.py` below.

```
--- utils.py    (original)
+++ utils.py    (refactored)
@@ -28,10 +28,10 @@
 import subprocess
 import sys
 import tarfile
-import urllib
-import urllib2
-
-from urllib2 import HTTPError
+import urllib.request, urllib.parse, urllib.error
+import urllib.request, urllib.error, urllib.parse
+
+from urllib.error import HTTPError

 # Python less than version 3 must import OSError
 if sys.version_info[0] < 3:
@@ -74,7 +74,7 @@
        try:
            response = json.loads(response)
        except:
-           print("Error parsing response for url %s, exiting." %(url))
+           print(("Error parsing response for url %s, exiting." %(url)))
            sys.exit(1)

        # If we have a next url
@@ -128,16 +128,16 @@
         do_stream = True

     if data != None:
-        args = urllib.urlencode(data)
-        request = urllib2.Request(url=url,
+        args = urllib.parse.urlencode(data)
+        request = urllib.request.Request(url=url,
                                   data=args,
                                   headers=headers)
     else:
-        request = urllib2.Request(url=url,
+        request = urllib.request.Request(url=url,
                                   headers=headers)

     try:
-        response = urllib2.urlopen(request)
+        response = urllib.request.urlopen(request)

     # If we have an HTTPError, try to follow the response
     except HTTPError as error:\
```

**Comment by vsoch** [comment]
hey @ashiklom! Could you retry this on the development branch? We no longer have this cli.py, nor do we have utils (it was renamed to suitls to deal with a conflict) so the bug might not be there anymore. Let's update this PR for the development branch, and then I will fix any issues right away!

**Comment by ashiklom** [comment]
@vsoch Thanks for getting back to me! Yes, everything seems to be working fine off the development branch, so I'll go ahead and close this issue.
