### ISSUE TITLE
busybox replace ash by bash, it's possible ?

### ISSUE THREAD

**Issue by sazearte** [apptainer/singularity#696]
Hello, i create small image with busybox.

but my image have ash shell, can i install bash ?
i try to copy binnary of bash (and there dependency) in my image, but when i run /bin/bash command i have this error
`/bin/sh: /bin/bash: not found`

if i modify local variable SHELL i have this error :
```
ERROR: Shell does not exist in container: /bin/bash
ERROR: Using /bin/sh instead...
```

**Comment by vsoch** [comment]
This may not be exactly what you want, but if you use alpine you get busybox and bash both. Here is my SIngularity build file:

```
Bootstrap: docker
From: alpine:latest

%post
apk update
apk add bash
apk add bash-doc
apk add bash-completion
```
and then to create
```
singularity create alpine.img
sudo singularity bootstrap alpine.img Singularity
```

and then you have both!

```
vanessa@vanessa-ThinkPad-T450s:~/Desktop$ singularity shell alpine.img 
Singularity: Invoking an interactive shell within container...

Singularity alpine.img:~/Desktop> which bash
/bin/bash
Singularity alpine.img:~/Desktop> which busybox
/bin/busybox
Singularity alpine.img:~/Desktop> 
```

**Comment by sazearte** [comment]
it's not work for me :
```
Bootstrap initialization
Checking bootstrap definition
Executing Prebootstrap module
Executing Bootstrap 'docker' module
From: alpine:latest
library/alpine:latest
Traceback (most recent call last):
  File "/usr/local/libexec/singularity/python/cli.py", line 198, in <module>
    main()
  File "/usr/local/libexec/singularity/python/cli.py", line 146, in main
    auth=doauth)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 156, in get_manifest
    permission="pull")
  File "/usr/local/libexec/singularity/python/docker/api.py", line 63, in get_token
    response = api_get(base,default_header=False)
  File "/usr/local/libexec/singularity/python/utils.py", line 143, in api_get
    response = urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
Executing Postbootstrap module
ERROR: Container does not contain the valid minimum requirement of /bin/sh
```

i use bootstrap busybox :

```
BootStrap: busybox
MirrorURL: file:///home/robert/busybox/busybox-x86_64


%post
    echo "Hello from inside the container"

```

but i have ash shell not bash

**Comment by vsoch** [comment]
Can you install development branch? We don't even have cli.py in the python bits anymore. Then please try again.

**Comment by truatpasteurdotfr** [comment]
@sazearte you are using singularity 2.2 ? just apply this workaround
reduce the bootstrap file to:
```
#bb.def
BootStrap: busybox
MirrorURL: file:///home/robert/busybox/busybox-x86_64
```
then:
```
sudo singularity create bb.img 
sudo singularity bootstrap bb.img bb.def
sudo singularity exec -w bb.img sh -c 'apk update && apk upgrade && apk add bash bash-doc bash-completion '

**Comment by sazearte** [comment]
truatpasteurdotfr, thanks for your help but in my busybox image, apk (or yum) is not installed, i have this error :
sh: apk: not found

vsoch i use latest stable version : 2.2.1

**Comment by vsoch** [comment]
@sazearte did you try my suggestion?

**Comment by vsoch** [comment]
and please use development branch:

```
git clone -b development https://www.github.com/singularityware/singularity.git
cd singularity
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install
```

**Comment by truatpasteurdotfr** [comment]
my bad sorry for the confusion, use @vsoch alpine container as:
alpine.def
```
Bootstrap: docker
From: alpine:latest
```

then
```
sudo singularity create alpine.img 
sudo singularity bootstrap alpine.img apline.def
sudo singularity exec -w alpine.img sh -c 'apk update && apk upgrade && apk add bash bash-doc bash-completion ' 
```

**Comment by dtrudg** [comment]
Closing this issue as it is against an old release of Singularity, and I believe the bootstrap from docker://alpine as above works for this.. Please let us know if you have an issues on the current 2.4.x release Thank you all.
