### ISSUE TITLE
python test suite fails on centos6

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#906]
## Version of Singularity:

Current development branch

### Expected behavior

test suite passes

### Actual behavior

Python unit tests fail with the following output:
```
################################################################################
Checking Python unit tests (script: 05-python-units.sh, testdir: /tmp/stest.B2E2Ko)

 + python2 -m unittest tests.test_json                                                           (retval=0) OK
 + python2 -m unittest tests.test_helpers                                                        (retval=0) OK
 + python2 -m unittest tests.test_base                                                           (retval=0) OK
 + python2 -m unittest tests.test_core                                                         (retval=255) ERROR
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.6/unittest.py", line 874, in <module>
    main(module=None)
  File "/usr/lib64/python2.6/unittest.py", line 815, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.6/unittest.py", line 842, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.6/unittest.py", line 848, in createTests
    self.module)
  File "/usr/lib64/python2.6/unittest.py", line 612, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.6/unittest.py", line 575, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "tests/test_core.py", line 328
    bad_json = {"Wakkawakkawakka'}": [{True}, "2", 3]}
                                           ^
SyntaxError: invalid syntax
Full output in: /tmp/stest.B2E2Ko
ERROR: Failed running test: 05-python-units.sh
make: *** [test] Error 1

```

### Steps to reproduce behavior

On a centos6 machine, after 'sudo make install' run 'make test'.

**Comment by DrDaveD** [comment]
If I quote the bad json line to make it a string, then it fails a little later on a pylint step:
```
Skipping python3 tests: not installed
 + pylint /cloud/login/dwd/work/singularity/libexec/python --errors-only --ignore tests --dis    (retval=2) ERROR
No config file found, using default configuration
************* Module python.docker.api
E: 70, 4: Use of super on an old style class (super-on-old-class)
************* Module python.shub.api
E: 66, 4: Use of super on an old style class (super-on-old-class)
E:109,44: Undefined variable 'image' (undefined-variable)
Full output in: /tmp/stest.TomEnZ
ERROR: Failed running test: 05-python-units.sh
make: *** [test] Error 1
```
I don't know how many other problems there might be.

**Comment by vsoch** [comment]
oh that's interesting, it looks like Super has issues with different python versions - I didn't know this!

https://stackoverflow.com/questions/54867/what-is-the-difference-between-old-style-and-new-style-classes-in-python

I agree with your fix for now - disable and then we can address the underlying issues within the tests.

**Comment by vsoch** [comment]
Is this limited to the test suite? I would be most concerned if python code in singularity proper were not compatible. We haven't even thought about the test suites to be honest, I didn't think they ran anywhere other than travis! :P

**Comment by dtrudg** [comment]
Closing as this is related only to the deprecated 2.x codebase.
