### ISSUE TITLE
Except the index.docker.io, other docker registry can not be used when importing image

### ISSUE THREAD

**Issue by zhcf** [apptainer/singularity#932]
version 2.3.2
[root@testcomputenode01 opt]# singularity import test.img docker://registry.docker-cn.com/centos
Docker image path: index.docker.io/registry.docker-cn.com/centos:latest

**Comment by vsoch** [comment]
The uri is parsed by way of splitting on `/`. So if you provide an image without a tag, it will infer the registry is the namespace, and the namespace the image. You need to ask for a specific tag:

```
docker://registry.docker-cn.com/centos:latest
```
so the parsing is done correctly. It's also best practice to be most specific in the versions you are asking for, to improve reproducibility. Please try with the tag and update the issue.

**Comment by zhcf** [comment]
Hi vsoch,
It does not work, still the same issue.
[root@localhost ~]# docker pull registry.docker-cn.com/library/centos:latest
latest: Pulling from library/centos
d9aaf4d82f24: Pull complete 
Digest: sha256:eba772bac22c86d7d6e72421b4700c3f894ab6e35475a34014ff8de74c10872e
Status: Downloaded newer image for registry.docker-cn.com/library/centos:latest
[root@localhost ~]# singularity pull docker://registry.docker-cn.com/centos:latest
Traceback (most recent call last):
  File "/usr/local/libexec/singularity/python/size.py", line 90, in <module>
    main()
  File "/usr/local/libexec/singularity/python/size.py", line 82, in main
    contentfile=LAYERFILE)
  File "/usr/local/libexec/singularity/python/docker/main.py", line 57, in SIZE
    client = DockerApiConnection(image=image,auth=auth)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 83, in __init__
    self.load_image(kwargs['image'])
  File "/usr/local/libexec/singularity/python/docker/api.py", line 120, in load_image
    self.update_token()
  File "/usr/local/libexec/singularity/python/docker/api.py", line 131, in update_token
    response = self.get_tags(return_response=True)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 217, in get_tags
    return_response=return_response)
  File "/usr/local/libexec/singularity/python/base.py", line 247, in get
    return_response=return_response)
  File "/usr/local/libexec/singularity/python/base.py", line 277, in submit_request
    response = urlopen(request)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by vsoch** [comment]
Is there any reason you are specifying registry.docker.cn? As far as I know that isn't the right one, but maybe there is something I am not aware of. Could you please try just pulling debian with a tag? It will default to namespace "library" and the default registry.

**Comment by vsoch** [comment]
And i'm seeing I copy pasted that 20 days ago, apologies for that!

**Comment by dtrudg** [comment]
Hi @zhcf - closing this as I believe it is addressed by the information provided by .@vsoch and changes that have been merged into the 2.4 releases of Singularity. Let us know if you have any remaining issues. Thanks!
